// This file is auto-generated by @hey-api/openapi-ts

export const ErrorSchema = {
    type: 'object',
    required: ['kind', 'path'],
    properties: {
        kind: {
            type: 'string',
            enum: ['not_found', 'unauthorized', 'validation_error', 'conflict', 'cap_reached', 'undo_window_expired', 'invalid_transition', 'rate_limited', 'provider_unavailable']
        },
        path: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const AiRunStatusSchema = {
    type: 'string',
    description: `Wire status is always terminal (synchronous execution). The full 5-state lifecycle (queued/running/...) is a server-side telemetry concern on the persisted run record, not exposed on the response.
`,
    enum: ['succeeded', 'failed', 'cancelled']
} as const;

export const AiRunEnvelopeSchema = {
    type: 'object',
    description: `Telemetry envelope embedded (as \`aiRun\`) in every AI operation's response. Execution is synchronous; \`status\` is terminal (\`succeeded\`/\`failed\`/\`cancelled\`) by the time the response returns.
`,
    required: ['provider', 'model', 'status', 'estimatedCostUsd', 'synthetic'],
    properties: {
        provider: {
            type: 'string',
            description: 'e.g. claude_cli',
            'fake.': null
        },
        model: {
            type: 'string'
        },
        status: {
            '$ref': '#/components/schemas/AiRunStatus'
        },
        startedAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        finishedAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        durationMs: {
            type: ['integer', 'null']
        },
        estimatedCostUsd: {
            type: 'number'
        },
        actualCostUsd: {
            type: ['number', 'null']
        },
        synthetic: {
            type: 'boolean',
            description: 'True iff produced by the FakeProvider (never satisfies evidence/approval).'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    required: ['name', 'email', 'initials', 'city', 'current', 'years', 'comp_floor', 'target_titles'],
    properties: {
        name: {
            type: 'string'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        initials: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        current: {
            type: 'string'
        },
        years: {
            type: 'number'
        },
        comp_floor: {
            type: 'number'
        },
        target_titles: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const StageSchema = {
    type: 'string',
    description: `Settled application-stage taxonomy (state-machines.md#application-stages is normative over the mock's coarser 8-value enum). Lowercase wire values; multiword stages use snake_case.
`,
    enum: ['saved', 'drafting', 'applied', 'screening', 'interview', 'offer', 'won', 'rejected', 'ghosted', 'withdrew', 'dismissed', 'offer_rescinded']
} as const;

export const TransitionSourceSchema = {
    type: 'string',
    description: 'Who/what drove the transition (aligned with the settled machine sources).',
    enum: ['user', 'user_correction', 'user_reactivation', 'system']
} as const;

export const StageTransitionSchema = {
    type: 'object',
    description: `One appended, immutable row of an application's stage-transition audit log. Corrections are compensating transitions referencing the prior row.
`,
    required: ['id', 'applicationId', 'toStage', 'source', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        applicationId: {
            type: 'string',
            format: 'uuid'
        },
        fromStage: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/Stage'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Prior stage; null for the initial SAVED/DRAFTING entry.'
        },
        toStage: {
            '$ref': '#/components/schemas/Stage'
        },
        source: {
            '$ref': '#/components/schemas/TransitionSource'
        },
        reason: {
            type: 'string'
        },
        reasons: {
            type: 'array',
            items: {
                type: 'string'
            },
            maxItems: 8,
            description: 'D16 chip reasons (dismiss/withdraw).'
        },
        resumeId: {
            type: ['string', 'null'],
            format: 'uuid',
            description: 'Resume snapshotted at APPLIED (required by the request when target is APPLIED).'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const TransitionInputSchema = {
    type: 'object',
    required: ['targetStage', 'expectedVersion'],
    properties: {
        targetStage: {
            '$ref': '#/components/schemas/Stage'
        },
        expectedVersion: {
            type: 'integer',
            description: 'Optimistic-concurrency guard; must equal Application.version or 409 `conflict`.'
        },
        source: {
            allOf: [
                {
                    '$ref': '#/components/schemas/TransitionSource'
                }
            ],
            default: 'user'
        },
        reason: {
            type: 'string'
        },
        reasons: {
            type: 'array',
            items: {
                type: 'string'
            },
            maxItems: 8
        },
        resumeId: {
            type: 'string',
            format: 'uuid',
            description: 'Required when `targetStage` = applied (locks the submitted-resume snapshot).'
        }
    },
    if: {
        properties: {
            targetStage: {
                const: 'applied'
            }
        },
        required: ['targetStage']
    },
    then: {
        required: ['resumeId']
    }
} as const;

export const TransitionResultSchema = {
    type: 'object',
    required: ['application', 'transition'],
    properties: {
        application: {
            '$ref': '#/components/schemas/ApplicationView'
        },
        transition: {
            '$ref': '#/components/schemas/StageTransition'
        }
    }
} as const;

export const ApplicationFlagSchema = {
    type: 'string',
    enum: ['stale', 'offer']
} as const;

export const SalaryPointSchema = {
    type: 'object',
    required: ['value', 'extra'],
    properties: {
        value: {
            type: 'integer',
            description: 'Full dollars.'
        },
        extra: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const SalaryRangeSchema = {
    type: 'object',
    required: ['min', 'max', 'extra'],
    properties: {
        min: {
            type: 'integer',
            description: 'Full dollars.'
        },
        max: {
            type: 'integer',
            description: 'Full dollars.'
        },
        extra: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const SalarySchema = {
    description: 'Structured compensation; null on the wire means undisclosed.',
    oneOf: [
        {
            '$ref': '#/components/schemas/SalaryPoint'
        },
        {
            '$ref': '#/components/schemas/SalaryRange'
        }
    ]
} as const;

export const ApplicationSchema = {
    type: 'object',
    description: 'Stored application record (ADR-006 stage 3, fully normalized).',
    required: ['id', 'jobId', 'resumeId', 'stage', 'version', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        jobId: {
            type: 'string',
            format: 'uuid',
            description: 'FK -> Job.id.'
        },
        resumeId: {
            type: ['string', 'null'],
            format: 'uuid',
            description: 'FK -> Resume.id; null when none yet.'
        },
        stage: {
            '$ref': '#/components/schemas/Stage'
        },
        version: {
            type: 'integer',
            description: 'Optimistic-concurrency counter; bumped on every transition (see TransitionInput.expectedVersion).'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            description: "Replaces the mock's relative `days`; the client derives age."
        },
        flag: {
            '$ref': '#/components/schemas/ApplicationFlag'
        },
        contact: {
            type: 'string'
        },
        coachNudge: {
            type: 'boolean'
        },
        resurrected: {
            type: 'boolean'
        },
        outcome: {
            type: 'string',
            enum: ['won', 'rejected', 'withdrawn'],
            description: 'ORI-009 archive bucket; present only on archived entries.'
        },
        outcomeAt: {
            type: 'string',
            format: 'date-time'
        },
        outcomeReason: {
            type: 'string'
        },
        outcomeReasons: {
            type: 'array',
            items: {
                type: 'string'
            },
            maxItems: 8,
            description: 'D16 user-chosen reason chips (max 8).'
        },
        systemReasons: {
            type: 'array',
            items: {
                type: 'string'
            },
            description: 'D16 system-applied chips -- separate tier, not counted in the user 8.'
        },
        submittedSnapshotId: {
            type: 'string',
            description: 'D10 FK -> ResumeSnapshot.id, set at APPLIED.'
        },
        searchId: {
            type: 'string',
            format: 'uuid',
            description: 'D15 FK -> Search.id (non-null in practice).'
        }
    }
} as const;

export const ApplicationViewSchema = {
    description: `Read model -- an Application joined with its Job and Resume (equivalent of GET /applications/{id}?expand=job,resume) with the job's display fields flattened on.
`,
    allOf: [
        {
            '$ref': '#/components/schemas/Application'
        },
        {
            type: 'object',
            required: ['job', 'resume', 'company', 'role', 'location', 'salary', 'match', 'source', 'resumeName'],
            properties: {
                job: {
                    '$ref': '#/components/schemas/Job'
                },
                resume: {
                    oneOf: [
                        {
                            '$ref': '#/components/schemas/Resume'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                company: {
                    type: 'string'
                },
                role: {
                    type: 'string'
                },
                location: {
                    type: 'string'
                },
                salary: {
                    oneOf: [
                        {
                            '$ref': '#/components/schemas/Salary'
                        },
                        {
                            type: 'null'
                        }
                    ]
                },
                match: {
                    type: 'integer'
                },
                source: {
                    type: 'string',
                    description: 'Origin ATS/board (greenhouse',
                    workday: null,
                    '...).': null
                },
                resumeName: {
                    type: 'string'
                }
            }
        }
    ]
} as const;

export const CreateApplicationInputSchema = {
    type: 'object',
    required: ['company', 'role', 'location', 'salary', 'match', 'source'],
    properties: {
        company: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        salary: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/Salary'
                },
                {
                    type: 'null'
                }
            ]
        },
        match: {
            type: 'integer'
        },
        source: {
            type: 'string'
        },
        resumeId: {
            type: ['string', 'null'],
            format: 'uuid',
            description: 'Selected resume; null when none yet.'
        },
        searchId: {
            type: 'string',
            format: 'uuid',
            description: 'D15 target saved search; defaults to last-used / auto-created "My jobs".'
        }
    }
} as const;

export const MarkWonInputSchema = {
    type: 'object',
    properties: {
        startDate: {
            type: 'string',
            format: 'date'
        },
        negotiatedComp: {
            description: 'Negotiated compensation; structured Salary carries qualifiers (equity, sign-on) via SalaryPoint.extra.',
            oneOf: [
                {
                    '$ref': '#/components/schemas/Salary'
                },
                {
                    type: 'null'
                }
            ]
        },
        whatWorked: {
            type: 'string'
        }
    }
} as const;

export const MarkWonResultSchema = {
    type: 'object',
    required: ['application', 'undoToken', 'undoExpiresAt', 'undoWindowSeconds'],
    properties: {
        application: {
            '$ref': '#/components/schemas/ApplicationView'
        },
        undoToken: {
            type: 'string',
            format: 'uuid'
        },
        undoExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        undoWindowSeconds: {
            type: 'integer',
            description: '300 in the mock.'
        }
    }
} as const;

export const DismissResultSchema = {
    type: 'object',
    required: ['outcome'],
    properties: {
        outcome: {
            type: 'string',
            enum: ['removed', 'withdrew'],
            description: 'removed = pre-commit delete; withdrew = post-APPLIED archive.'
        }
    }
} as const;

export const TimelineEventSchema = {
    type: 'object',
    required: ['id', 'time', 'who', 'message'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        time: {
            type: 'string',
            format: 'date-time'
        },
        who: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        actor: {
            type: 'string',
            enum: ['you', 'coach-on-behalf', 'agent'],
            description: 'COA-036 structured attribution (client renders the badge copy).'
        }
    }
} as const;

export const InterviewTypeSchema = {
    type: 'string',
    enum: ['recruiter-screen', 'technical', 'onsite', 'final']
} as const;

export const InterviewFormatSchema = {
    type: 'string',
    enum: ['video', 'phone', 'onsite']
} as const;

export const InterviewStatusSchema = {
    type: 'string',
    enum: ['scheduled', 'completed', 'cancelled']
} as const;

export const InterviewRoundSchema = {
    type: 'object',
    required: ['id', 'appId', 'date', 'type', 'format', 'status'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        appId: {
            type: 'string',
            format: 'uuid'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        type: {
            '$ref': '#/components/schemas/InterviewType'
        },
        format: {
            '$ref': '#/components/schemas/InterviewFormat'
        },
        status: {
            '$ref': '#/components/schemas/InterviewStatus'
        }
    }
} as const;

export const ResumeSnapshotSchema = {
    type: 'object',
    description: 'D10 immutable copy of the resume captured at APPLIED.',
    required: ['id', 'applicationId', 'resumeId', 'name', 'body', 'templateVersion', 'capturedAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        applicationId: {
            type: 'string',
            format: 'uuid'
        },
        resumeId: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        templateVersion: {
            type: 'string',
            description: 'D17 provenance.'
        },
        capturedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ShortlistEntrySchema = {
    type: 'object',
    required: ['id', 'company', 'role', 'location', 'salary', 'match', 'saved', 'source'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            description: 'Shortlist entry id (DELETE /shortlist/{id}).'
        },
        jobId: {
            type: 'string',
            format: 'uuid',
            description: 'FK -> Job.id (ADR-006).'
        },
        company: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        salary: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/Salary'
                },
                {
                    type: 'null'
                }
            ]
        },
        match: {
            type: 'integer'
        },
        saved: {
            type: 'string',
            format: 'date-time'
        },
        source: {
            type: 'string',
            enum: ['you']
        },
        why: {
            type: 'string'
        },
        stale: {
            type: 'boolean'
        }
    }
} as const;

export const JobCaptureMethodSchema = {
    type: 'string',
    enum: ['url', 'jd-text', 'extension', 'email-forward']
} as const;

export const JobWorkModeSchema = {
    type: 'string',
    enum: ['remote', 'hybrid', 'onsite']
} as const;

export const JobInboxItemSchema = {
    type: 'object',
    required: ['company', 'role', 'location', 'salary', 'match', 'source', 'posted'],
    properties: {
        jobId: {
            type: 'string',
            format: 'uuid'
        },
        company: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        salary: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/Salary'
                },
                {
                    type: 'null'
                }
            ]
        },
        match: {
            type: 'integer'
        },
        source: {
            type: 'string',
            description: 'Origin board (greenhouse',
            workday: null,
            hospital: null,
            '...).': null
        },
        isNew: {
            type: 'boolean'
        },
        posted: {
            type: 'string',
            format: 'date-time'
        },
        capturedVia: {
            '$ref': '#/components/schemas/JobCaptureMethod'
        },
        capturedAt: {
            type: 'string',
            format: 'date-time'
        },
        sourceUrl: {
            type: 'string',
            format: 'uri'
        },
        workMode: {
            '$ref': '#/components/schemas/JobWorkMode'
        },
        employmentType: {
            type: 'string'
        },
        seniority: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        requirements: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        strengths: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        gaps: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        jd: {
            type: 'string',
            description: 'Raw JD text',
            'preserved verbatim at capture.': null
        }
    }
} as const;

export const EmploymentSchema = {
    type: 'object',
    description: 'ADR-006 -- three independent atomic axes.',
    required: ['classification', 'cadence', 'commitment'],
    properties: {
        classification: {
            type: 'string',
            enum: ['w2', 'contract', '1099']
        },
        cadence: {
            type: 'string',
            enum: ['hourly', 'salary']
        },
        commitment: {
            type: 'string',
            enum: ['full-time', 'part-time']
        }
    }
} as const;

export const JobLocationSchema = {
    type: 'object',
    required: ['raw'],
    properties: {
        raw: {
            type: 'string'
        },
        locality: {
            type: 'string'
        },
        region: {
            type: 'string'
        },
        country: {
            type: 'string'
        }
    }
} as const;

export const JobSourceSchema = {
    type: 'object',
    required: ['board', 'channel', 'capturedAt'],
    properties: {
        board: {
            type: 'string'
        },
        channel: {
            '$ref': '#/components/schemas/JobCaptureMethod'
        },
        url: {
            type: 'string',
            format: 'uri'
        },
        capturedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const JobMatchSchema = {
    type: 'object',
    required: ['score', 'strengths', 'gaps'],
    properties: {
        score: {
            type: 'integer'
        },
        strengths: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        gaps: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        kind: {
            type: 'string',
            enum: ['rough', 'deep'],
            description: 'D8 -- rough = free local heuristic; deep = paid LLM. Absent = rough.'
        }
    }
} as const;

export const JobSchema = {
    type: 'object',
    description: 'A captured posting -- the canonical resource (ADR-006).',
    required: ['id', 'company', 'title', 'location', 'workMode', 'employment', 'compensation', 'source', 'posted'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        company: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        location: {
            '$ref': '#/components/schemas/JobLocation'
        },
        workMode: {
            '$ref': '#/components/schemas/JobWorkMode'
        },
        employment: {
            '$ref': '#/components/schemas/Employment'
        },
        compensation: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/Salary'
                },
                {
                    type: 'null'
                }
            ]
        },
        seniority: {
            type: 'string'
        },
        source: {
            '$ref': '#/components/schemas/JobSource'
        },
        isNew: {
            type: 'boolean'
        },
        posted: {
            type: 'string',
            format: 'date-time'
        },
        summary: {
            type: 'string'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        requirements: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        description: {
            type: 'string',
            description: 'Verbatim JD text.'
        },
        match: {
            '$ref': '#/components/schemas/JobMatch'
        }
    }
} as const;

export const MatchRubricRowSchema = {
    type: 'object',
    required: ['label', 'score', 'note'],
    properties: {
        label: {
            type: 'string'
        },
        score: {
            type: 'integer'
        },
        note: {
            type: 'string'
        }
    }
} as const;

export const MatchGapSchema = {
    type: 'object',
    required: ['severity', 'text'],
    properties: {
        severity: {
            type: 'string',
            enum: ['high', 'medium', 'low']
        },
        text: {
            type: 'string'
        }
    }
} as const;

export const MatchReportSchema = {
    type: 'object',
    required: ['resumeId', 'jobId', 'score', 'rubric', 'gaps', 'strengths'],
    properties: {
        resumeId: {
            type: 'string',
            format: 'uuid'
        },
        jobId: {
            type: 'string',
            format: 'uuid'
        },
        score: {
            type: 'integer'
        },
        rubric: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/MatchRubricRow'
            }
        },
        gaps: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/MatchGap'
            }
        },
        strengths: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const CostPreviewItemSchema = {
    type: 'object',
    required: ['resumeId', 'model', 'estCostUsd'],
    properties: {
        resumeId: {
            type: 'string',
            format: 'uuid',
            description: 'The resume this line prices (label was UI copy).'
        },
        model: {
            type: 'string'
        },
        estCostUsd: {
            type: 'number'
        }
    }
} as const;

export const CostPreviewSchema = {
    type: 'object',
    description: 'D8b consent panel payload, returned before any paid LLM run.',
    required: ['items', 'totalUsd', 'capRemainingUsd', 'overCap'],
    properties: {
        items: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CostPreviewItem'
            }
        },
        totalUsd: {
            type: 'number'
        },
        capRemainingUsd: {
            type: 'number'
        },
        overCap: {
            type: 'boolean'
        }
    }
} as const;

export const DeepMatchResultSchema = {
    type: 'object',
    required: ['jobId', 'resumeId', 'score', 'kind', 'strengths', 'gaps', 'costUsd', 'aiRun'],
    properties: {
        jobId: {
            type: 'string',
            format: 'uuid'
        },
        resumeId: {
            type: 'string',
            format: 'uuid'
        },
        score: {
            type: 'integer'
        },
        kind: {
            type: 'string',
            enum: ['deep']
        },
        strengths: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        gaps: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        costUsd: {
            type: 'number'
        },
        aiRun: {
            '$ref': '#/components/schemas/AiRunEnvelope'
        }
    }
} as const;

export const AgentStateSchema = {
    type: 'string',
    enum: ['running', 'demand', 'paused', 'error']
} as const;

export const AgentTrustTierSchema = {
    type: 'string',
    enum: ['observe', 'suggest', 'act-with-approval', 'autonomous']
} as const;

export const AgentSchema = {
    type: 'object',
    required: ['id', 'name', 'state', 'lastActivity', 'actions', 'costUsd', 'description'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        state: {
            '$ref': '#/components/schemas/AgentState'
        },
        lastActivity: {
            type: 'string',
            format: 'date-time'
        },
        actions: {
            type: 'integer'
        },
        costUsd: {
            type: 'number',
            description: "Agent's month-to-date cost",
            'USD (was preformatted "$0.00").': null
        },
        description: {
            type: 'string'
        },
        live: {
            type: 'boolean'
        },
        trustTier: {
            '$ref': '#/components/schemas/AgentTrustTier'
        }
    }
} as const;

export const TrustTierRungSchema = {
    type: 'object',
    description: 'One rung of the ladder. label/blurb were UI copy (client-owned).',
    required: ['tier'],
    properties: {
        tier: {
            '$ref': '#/components/schemas/AgentTrustTier'
        }
    }
} as const;

export const AgentTrustTierViewSchema = {
    type: 'object',
    required: ['agentId', 'currentTier', 'ladder'],
    properties: {
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        currentTier: {
            '$ref': '#/components/schemas/AgentTrustTier'
        },
        unlockedAt: {
            type: 'string',
            format: 'date-time'
        },
        ladder: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TrustTierRung'
            }
        }
    }
} as const;

export const AgentTrustTierUpdateSchema = {
    type: 'object',
    required: ['agentId', 'currentTier', 'status', 'message'],
    properties: {
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        currentTier: {
            '$ref': '#/components/schemas/AgentTrustTier'
        },
        status: {
            type: 'string',
            description: 'State model DEFERRED (founder ruled 2026-07-04, DECISIONS-NEEDED'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const AgentLogKindSchema = {
    type: 'string',
    enum: ['auto', 'await', 'success', 'skipped']
} as const;

export const AgentLogEntrySchema = {
    type: 'object',
    required: ['time', 'agentId', 'kind', 'message', 'ref'],
    properties: {
        time: {
            type: 'string',
            format: 'date-time'
        },
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        kind: {
            '$ref': '#/components/schemas/AgentLogKind'
        },
        message: {
            type: 'string'
        },
        ref: {
            type: 'string',
            description: 'Opaque cross-reference to the acted-upon entity.'
        }
    }
} as const;

export const AgentPermissionSchema = {
    type: 'object',
    required: ['permission', 'granted'],
    properties: {
        permission: {
            type: 'string'
        },
        granted: {
            type: 'boolean'
        },
        requiredTier: {
            '$ref': '#/components/schemas/AgentTrustTier'
        }
    }
} as const;

export const ReviewQueueItemSchema = {
    type: 'object',
    required: ['id', 'agentId', 'message', 'time'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            description: 'Queue entry id (approve/reject by /agents/review-queue/{id}).'
        },
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        message: {
            type: 'string'
        },
        time: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ResumeTagSchema = {
    type: 'string',
    enum: ['MASTER', 'DEFAULT', 'VARIANT', 'TAILORED', 'DRAFT', 'FORMAT']
} as const;

export const ResumeSchema = {
    type: 'object',
    description: `In the resume-lifecycle model (RES-034, ADR-007/008) a non-FORMAT Resume IS a projection -- a curated selection over career history.
`,
    required: ['id', 'name', 'subtitle', 'version', 'usedIn', 'updated', 'tag'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        subtitle: {
            type: 'string',
            description: 'User-visible resume descriptor (data',
            'not UI chrome).': null
        },
        version: {
            type: 'string'
        },
        usedIn: {
            type: 'integer'
        },
        updated: {
            type: 'string',
            format: 'date-time'
        },
        tag: {
            '$ref': '#/components/schemas/ResumeTag'
        },
        match: {
            type: 'integer'
        },
        body: {
            type: 'string'
        },
        sourceUploadId: {
            type: 'string',
            format: 'uuid',
            description: 'RES-034 upload provenance.'
        },
        templateId: {
            type: 'string',
            format: 'uuid',
            description: 'TPL-002 render template.'
        },
        targetRole: {
            type: 'string'
        },
        scoringEnabled: {
            type: 'boolean',
            description: 'D21 -- participates in match scoring; default ON, MASTER-only.'
        }
    }
} as const;

export const ResumeUploadSchema = {
    type: 'object',
    required: ['id', 'filename', 'uploadedAt', 'parsed', 'sizeBytes'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        filename: {
            type: 'string'
        },
        uploadedAt: {
            type: 'string',
            format: 'date-time'
        },
        parsed: {
            type: 'boolean'
        },
        sizeBytes: {
            type: 'integer'
        }
    }
} as const;

export const CareerHistoryItemSchema = {
    type: 'object',
    required: ['id', 'kind', 'title', 'bullets', 'ordinal', 'sourceUploadIds'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        kind: {
            type: 'string',
            enum: ['experience', 'education', 'skill', 'project', 'summary']
        },
        title: {
            type: 'string'
        },
        org: {
            type: 'string'
        },
        bullets: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        ordinal: {
            type: 'integer'
        },
        sourceUploadIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            },
            description: 'RES-038 merge provenance.'
        }
    }
} as const;

export const ResumeExportSchema = {
    type: 'object',
    required: ['id', 'projectionId', 'templateId', 'templateVersion', 'filename', 'generatedAt', 'regenerable'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        projectionId: {
            type: 'string',
            format: 'uuid'
        },
        templateId: {
            type: 'string',
            format: 'uuid'
        },
        templateVersion: {
            type: 'string',
            description: 'D17 -- frozen per export.'
        },
        filename: {
            type: 'string'
        },
        generatedAt: {
            type: 'string',
            format: 'date-time'
        },
        regenerable: {
            type: 'boolean'
        }
    }
} as const;

export const ResumeTemplateSchema = {
    type: 'object',
    required: ['id', 'name', 'previewKind', 'description'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        previewKind: {
            type: 'string',
            enum: ['single-column', 'two-column', 'compact', 'modern']
        },
        description: {
            type: 'string'
        }
    }
} as const;

export const CoachThreadScopeSchema = {
    type: 'string',
    description: 'Note `résumé` with é -- verbatim from source; fixtures depend on the spelling.',
    enum: ['application', 'résumé', 'career-history', 'projection', 'contact', 'answer', 'project', 'accomplishment', 'prep', 'general']
} as const;

export const CoachThreadSchema = {
    type: 'object',
    required: ['id', 'title', 'scope', 'when'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string',
            description: 'Thread title (data',
            'client-owned copy stays as-is).': null
        },
        scope: {
            '$ref': '#/components/schemas/CoachThreadScope'
        },
        when: {
            type: 'string',
            format: 'date-time'
        },
        active: {
            type: 'boolean'
        }
    }
} as const;

export const CoachMessageSchema = {
    type: 'object',
    required: ['id', 'author', 'text'],
    properties: {
        id: {
            type: 'string'
        },
        author: {
            type: 'string',
            enum: ['user', 'bot']
        },
        text: {
            type: 'string'
        },
        draft: {
            type: 'string'
        },
        draftAttachments: {
            type: 'array',
            description: "COA-024 -- items to attach when sending from the user's OWN email client.",
            items: {
                type: 'object',
                required: ['name', 'kind'],
                properties: {
                    name: {
                        type: 'string'
                    },
                    kind: {
                        type: 'string',
                        enum: ['resume', 'cover-letter', 'file']
                    }
                }
            }
        },
        typing: {
            type: 'boolean'
        }
    }
} as const;

export const ContextCardSchema = {
    type: 'object',
    required: ['label', 'body'],
    properties: {
        label: {
            type: 'string'
        },
        body: {
            type: 'string'
        }
    }
} as const;

export const CoachSubjectSchema = {
    type: 'object',
    description: 'COA-031 -- the live "what am I looking at" descriptor.',
    required: ['scope', 'label'],
    properties: {
        scope: {
            '$ref': '#/components/schemas/CoachThreadScope'
        },
        id: {
            type: 'string'
        },
        label: {
            type: 'string'
        }
    }
} as const;

export const CoachDiffSchema = {
    type: 'object',
    required: ['field', 'before', 'after'],
    properties: {
        field: {
            type: 'string'
        },
        before: {
            type: 'string'
        },
        after: {
            type: 'string'
        }
    }
} as const;

export const CoachProposalSchema = {
    type: 'object',
    description: 'COA-032 -- reviewed (gate 1) before it is saved (gate 2).',
    required: ['id', 'subject', 'summary', 'diff', 'status'],
    properties: {
        id: {
            type: 'string'
        },
        subject: {
            '$ref': '#/components/schemas/CoachSubject'
        },
        summary: {
            type: 'string'
        },
        diff: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CoachDiff'
            }
        },
        status: {
            type: 'string',
            description: 'State model DEFERRED (founder ruled 2026-07-04, DECISIONS-NEEDED'
        }
    }
} as const;

export const ContactSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/ContactDraft'
        },
        {
            type: 'object',
            required: ['id', 'updated'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                updated: {
                    type: 'string',
                    format: 'date-time'
                },
                deletedAt: {
                    type: 'string',
                    format: 'date-time',
                    description: 'D24 soft-delete marker; set = in the trash.'
                }
            }
        }
    ]
} as const;

export const ContactDraftSchema = {
    type: 'object',
    required: ['name', 'role', 'org', 'email', 'phone', 'relationship', 'isReference', 'tags', 'links', 'notes'],
    properties: {
        name: {
            type: 'string'
        },
        role: {
            type: 'string'
        },
        org: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        phone: {
            type: 'string'
        },
        relationship: {
            type: 'string'
        },
        isReference: {
            type: 'boolean',
            description: 'References are a tagged role (CON-002).'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        links: {
            type: 'array',
            items: {
                type: 'object',
                required: ['label', 'url'],
                properties: {
                    label: {
                        type: 'string'
                    },
                    url: {
                        type: 'string',
                        format: 'uri'
                    }
                }
            }
        },
        notes: {
            type: 'string'
        }
    }
} as const;

export const AccomplishmentSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/AccomplishmentDraft'
        },
        {
            type: 'object',
            required: ['id', 'usedIn', 'updated'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                usedIn: {
                    type: 'integer'
                },
                updated: {
                    type: 'string',
                    format: 'date-time'
                },
                deletedAt: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        }
    ]
} as const;

export const AccomplishmentDraftSchema = {
    type: 'object',
    required: ['title', 'summary', 'tags', 'source'],
    properties: {
        title: {
            type: 'string'
        },
        summary: {
            type: 'string'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        source: {
            description: 'ACC-002 -- set when distilled from a Project (snapshot + backlink), else null.',
            oneOf: [
                {
                    type: 'object',
                    required: ['projectId'],
                    properties: {
                        projectId: {
                            type: 'string',
                            format: 'uuid'
                        }
                    }
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;

export const AccomplishmentDeriveResultSchema = {
    type: 'object',
    description: 'Response of deriveAccomplishmentFromProject (AI op); the accomplishment plus its run telemetry.',
    required: ['accomplishment', 'aiRun'],
    properties: {
        accomplishment: {
            '$ref': '#/components/schemas/Accomplishment'
        },
        aiRun: {
            '$ref': '#/components/schemas/AiRunEnvelope'
        }
    }
} as const;

export const AnswerSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/AnswerDraft'
        },
        {
            type: 'object',
            required: ['id', 'updated'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                updated: {
                    type: 'string',
                    format: 'date-time'
                },
                deletedAt: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        }
    ]
} as const;

export const AnswerDraftSchema = {
    type: 'object',
    required: ['question', 'body', 'category', 'tags'],
    properties: {
        question: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        category: {
            type: 'string',
            enum: ['compensation', 'motivation', 'work-authorization', 'logistics', 'eeo', 'other']
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const ProjectSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/ProjectDraft'
        },
        {
            type: 'object',
            required: ['id', 'updated'],
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                updated: {
                    type: 'string',
                    format: 'date-time'
                },
                deletedAt: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        }
    ]
} as const;

export const ProjectDraftSchema = {
    type: 'object',
    description: 'PRJ-001 -- a per-employer brain-dump / evidence reservoir.',
    required: ['title', 'employer', 'body', 'tags'],
    properties: {
        title: {
            type: 'string'
        },
        employer: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    }
} as const;

export const CredentialSchema = {
    type: 'object',
    required: ['id', 'name', 'type', 'issuer', 'fileRef', 'updated'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        type: {
            type: 'string',
            enum: ['license', 'certification', 'transcript', 'portfolio', 'other']
        },
        issuer: {
            type: 'string'
        },
        expiry: {
            type: 'string',
            format: 'date'
        },
        fileRef: {
            type: 'string'
        },
        updated: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const LibraryKindSchema = {
    type: 'string',
    enum: ['contact', 'accomplishment', 'answer', 'project']
} as const;

export const TrashEntrySchema = {
    type: 'object',
    required: ['kind', 'id', 'label', 'deletedAt'],
    properties: {
        kind: {
            '$ref': '#/components/schemas/LibraryKind'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        label: {
            type: 'string'
        },
        deletedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const DeletionImpactSchema = {
    type: 'object',
    required: ['kind', 'id', 'dependents', 'total'],
    properties: {
        kind: {
            '$ref': '#/components/schemas/LibraryKind'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        dependents: {
            type: 'array',
            items: {
                type: 'object',
                required: ['kind', 'count', 'items'],
                properties: {
                    kind: {
                        '$ref': '#/components/schemas/LibraryKind'
                    },
                    count: {
                        type: 'integer'
                    },
                    items: {
                        type: 'array',
                        items: {
                            type: 'object',
                            required: ['id', 'label'],
                            properties: {
                                id: {
                                    type: 'string',
                                    format: 'uuid'
                                },
                                label: {
                                    type: 'string'
                                }
                            }
                        }
                    }
                }
            }
        },
        total: {
            type: 'integer'
        }
    }
} as const;

export const SearchCriteriaSchema = {
    type: 'object',
    required: ['titlesInclude', 'titlesExclude', 'locations', 'remotePolicy', 'maxCommuteMin', 'baseFloorUsd', 'baseCeilingUsd'],
    properties: {
        titlesInclude: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        titlesExclude: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        locations: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        remotePolicy: {
            type: 'string',
            description: 'Machine tokens; client maps to display copy.',
            enum: ['remote-ok', 'hybrid-ok', 'required']
        },
        maxCommuteMin: {
            type: 'integer'
        },
        baseFloorUsd: {
            type: 'number',
            description: 'Base salary floor',
            'USD (was string "$...").': null
        },
        baseCeilingUsd: {
            type: 'number',
            description: 'Base salary ceiling',
            'USD.': null
        },
        yearsExperienceMin: {
            type: 'integer',
            description: 'Lower bound of the years-experience band (was string "8-14 yrs").'
        },
        yearsExperienceMax: {
            type: 'integer',
            description: 'Upper bound of the years-experience band.'
        },
        scoringResumeIds: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            },
            description: 'D21 per-search override -- REPLACES the global eligible master set.'
        }
    }
} as const;

export const SearchSchema = {
    type: 'object',
    required: ['id', 'name', 'criteria', 'jobsInInbox', 'activeApplications', 'shortlisted', 'offers', 'spendMoUsd'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        state: {
            type: 'string',
            enum: ['active', 'paused'],
            description: 'Defaults to active when absent. No pause/activate mutation is frozen (see DECISIONS-NEEDED.md).'
        },
        criteria: {
            '$ref': '#/components/schemas/SearchCriteria'
        },
        jobsInInbox: {
            type: 'integer'
        },
        activeApplications: {
            type: 'integer'
        },
        shortlisted: {
            type: 'integer'
        },
        offers: {
            type: 'integer'
        },
        spendMoUsd: {
            type: 'number',
            description: 'Month-to-date spend for this search',
            'USD (was "$0.00").': null
        }
    }
} as const;

export const CreateSearchInputSchema = {
    type: 'object',
    required: ['name', 'criteria'],
    properties: {
        name: {
            type: 'string'
        },
        criteria: {
            description: 'Partial criteria; unset fields take blank defaults.',
            '$ref': '#/components/schemas/SearchCriteria'
        }
    }
} as const;

export const NotificationSchema = {
    type: 'object',
    required: ['id', 'kind', 'title', 'message', 'actor'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        kind: {
            type: 'string',
            enum: ['reply', 'agent', 'match', 'cal']
        },
        title: {
            type: 'string'
        },
        message: {
            type: 'string'
        },
        actor: {
            type: 'string'
        },
        unread: {
            type: 'boolean'
        }
    }
} as const;

export const IntegrationRowSchema = {
    type: 'object',
    required: ['name', 'description', 'state'],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        state: {
            type: 'string',
            enum: ['connected', 'not-connected', 'auto']
        },
        account: {
            type: 'string'
        },
        lastSync: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ProviderRowSchema = {
    type: 'object',
    required: ['provider', 'model', 'state'],
    properties: {
        provider: {
            type: 'string'
        },
        model: {
            type: 'string'
        },
        state: {
            type: 'string',
            enum: ['connected', 'not-connected', 'error']
        },
        balanceUsd: {
            type: 'number',
            description: 'Prepaid provider balance',
            'USD (was "$...").': null
        },
        error: {
            type: 'string'
        }
    }
} as const;

export const RoutingRowSchema = {
    type: 'object',
    description: 'Per-task provider routing (label/value were generic display pairs; now semantic).',
    required: ['task', 'model'],
    properties: {
        task: {
            type: 'string',
            description: 'Task key',
            'e.g. "Match scoring".': null
        },
        model: {
            type: 'string',
            description: 'Model routed to that task.'
        }
    }
} as const;

export const UsageRowSchema = {
    type: 'object',
    required: ['service', 'model', 'count', 'tokens', 'costUsd'],
    properties: {
        service: {
            type: 'string'
        },
        model: {
            type: 'string'
        },
        count: {
            type: 'integer'
        },
        tokens: {
            type: 'integer'
        },
        costUsd: {
            type: 'number'
        }
    }
} as const;

export const PrivacyToggleSchema = {
    type: 'object',
    description: `Toggle STATE is data; the title/description copy is client-owned, keyed off \`key\`.
`,
    required: ['key', 'on'],
    properties: {
        key: {
            type: 'string',
            description: 'Stable toggle key the client maps to copy.'
        },
        on: {
            type: 'boolean'
        }
    }
} as const;

export const InvoiceRowSchema = {
    type: 'object',
    required: ['date', 'description', 'amountUsd'],
    properties: {
        date: {
            type: 'string',
            format: 'date-time'
        },
        description: {
            type: 'string'
        },
        amountUsd: {
            type: 'number'
        }
    }
} as const;

export const NotifPrefSchema = {
    type: 'object',
    required: ['id', 'category', 'emailEnabled', 'inAppEnabled'],
    properties: {
        id: {
            type: 'string'
        },
        category: {
            type: 'string',
            description: 'Category key (data; client owns the consequence copy).'
        },
        emailEnabled: {
            type: 'boolean'
        },
        inAppEnabled: {
            type: 'boolean'
        },
        emailLocked: {
            type: 'boolean'
        }
    }
} as const;

export const ExtensionTokenSchema = {
    type: 'object',
    required: ['id', 'label', 'createdAt'],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        label: {
            type: 'string'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        revokedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const EmailParserFallbackSchema = {
    type: 'object',
    description: 'D9b -- parser behavior once the monthly cap is hit.',
    required: ['mode'],
    properties: {
        mode: {
            type: 'string',
            enum: ['deterministic', 'cheap-model']
        },
        model: {
            type: 'string',
            description: 'Cheap model id, present when mode = cheap-model.'
        }
    }
} as const;

export const SettingsSchema = {
    type: 'object',
    required: ['profile', 'integrations', 'providers', 'routing', 'usage', 'monthSpendUsd', 'monthlyCapUsd', 'privacy', 'privacyLastUpdated', 'plan', 'invoices', 'notifPrefs', 'extensionTokens', 'emailParserFallback'],
    properties: {
        profile: {
            type: 'object',
            required: ['name', 'email', 'phone', 'timezone', 'currentRole', 'targetTitles', 'compFloorUsd'],
            properties: {
                name: {
                    type: 'string'
                },
                email: {
                    type: 'string',
                    format: 'email'
                },
                phone: {
                    type: 'string'
                },
                timezone: {
                    type: 'string'
                },
                currentRole: {
                    type: 'string'
                },
                targetTitles: {
                    type: 'array',
                    items: {
                        type: 'string'
                    }
                },
                compFloorUsd: {
                    type: 'number',
                    description: 'Compensation floor',
                    'USD (was string).': null
                }
            }
        },
        integrations: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/IntegrationRow'
            }
        },
        providers: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ProviderRow'
            }
        },
        routing: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/RoutingRow'
            }
        },
        usage: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UsageRow'
            }
        },
        monthSpendUsd: {
            type: 'number'
        },
        monthlyCapUsd: {
            type: 'number'
        },
        privacy: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/PrivacyToggle'
            }
        },
        privacyLastUpdated: {
            type: 'string',
            format: 'date-time'
        },
        plan: {
            type: 'object',
            required: ['name', 'priceUsd', 'description', 'nextCharge'],
            properties: {
                name: {
                    type: 'string'
                },
                priceUsd: {
                    type: 'number'
                },
                description: {
                    type: 'string'
                },
                nextCharge: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        },
        invoices: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/InvoiceRow'
            }
        },
        notifPrefs: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/NotifPref'
            }
        },
        extensionTokens: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/ExtensionToken'
            }
        },
        emailParserFallback: {
            '$ref': '#/components/schemas/EmailParserFallback'
        }
    }
} as const;

export const UsageAggregateSchema = {
    type: 'object',
    required: ['monthSpendUsd', 'monthlyCapUsd', 'tokensIn', 'tokensOut', 'avgPerSessionUsd'],
    properties: {
        monthSpendUsd: {
            type: 'number'
        },
        monthlyCapUsd: {
            type: 'number'
        },
        tokensIn: {
            type: 'integer'
        },
        tokensOut: {
            type: 'integer'
        },
        avgPerSessionUsd: {
            type: 'number',
            description: 'Average spend per session',
            'USD.': null
        }
    }
} as const;

export const DataExportRequestSchema = {
    type: 'object',
    required: ['url', 'requestedAt'],
    properties: {
        url: {
            type: 'string',
            format: 'uri'
        },
        requestedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;