// This file is auto-generated by @hey-api/openapi-ts

export type Accomplishment = {
    title: string;
    summary: string;
    tags: Array<(string)>;
    source: (Source1 | null);
    id: string;
    usedIn: number;
    updated: string;
    deletedAt?: (string | null);
};

/**
 * Response of deriveAccomplishmentFromProject (AI op); the accomplishment plus its run telemetry.
 */
export type AccomplishmentDeriveResult = {
    accomplishment: Accomplishment;
    aiRun: AiRunEnvelope;
};

export type AccomplishmentDraft = {
    title: string;
    summary: string;
    tags: Array<(string)>;
    source: (Source1 | null);
};

/**
 * Inline 202 response shape for ``deleteAccount`` (no named contract schema).
 */
export type AccountDeletionResult = {
    gracePeriodEndsAt: string;
};

/**
 * COA-036 structured attribution (client renders the badge copy).
 */
export type Actor = 'you' | 'coach-on-behalf' | 'agent';

/**
 * Inline requestBody for ``POST /shortlist`` (no named contract schema).
 */
export type AddToShortlistBody = {
    jobId?: (string | null);
    company: string;
    role: string;
    location: string;
    salary: (SalaryPoint | SalaryRange | null);
    match: number;
};

export type Agent = {
    id: string;
    name: string;
    state: AgentState;
    lastActivity: string;
    actions: number;
    costUsd: number;
    description: string;
    live?: (boolean | null);
    trustTier?: (AgentTrustTier | null);
};

export type AgentLogEntry = {
    time: string;
    agentId: string;
    kind: AgentLogKind;
    message: string;
    ref: string;
};

export type AgentLogKind = 'auto' | 'await' | 'success' | 'skipped';

export type AgentPermission = {
    permission: string;
    granted: boolean;
    requiredTier?: (AgentTrustTier | null);
};

export type AgentState = 'running' | 'demand' | 'paused' | 'error';

export type AgentTrustTier = 'observe' | 'suggest' | 'act-with-approval' | 'autonomous';

export type AgentTrustTierUpdate = {
    agentId: string;
    currentTier: AgentTrustTier;
    status: string;
    message: string;
};

export type AgentTrustTierView = {
    agentId: string;
    currentTier: AgentTrustTier;
    unlockedAt?: (string | null);
    ladder: Array<TrustTierRung>;
};

/**
 * Telemetry envelope embedded (as `aiRun`) in every AI operation's response. Execution is synchronous; `status` is terminal (`succeeded`/`failed`/`cancelled`) by the time the response returns.
 */
export type AiRunEnvelope = {
    provider: string;
    model: string;
    status: AiRunStatus;
    startedAt?: (string | null);
    finishedAt?: (string | null);
    durationMs?: (number | null);
    estimatedCostUsd: number;
    actualCostUsd?: (number | null);
    synthetic: boolean;
};

/**
 * Wire status is always terminal (synchronous execution). The full 5-state lifecycle (queued/running/...) is a server-side telemetry concern on the persisted run record, not exposed on the response.
 */
export type AiRunStatus = 'succeeded' | 'failed' | 'cancelled';

export type Answer = {
    question: string;
    body: string;
    category: Category;
    tags: Array<(string)>;
    id: string;
    updated: string;
    deletedAt?: (string | null);
};

export type AnswerDraft = {
    question: string;
    body: string;
    category: Category;
    tags: Array<(string)>;
};

export type ApplicationFlag = 'stale' | 'offer';

/**
 * Read model -- an Application joined with its Job and Resume (equivalent of GET /applications/{id}?expand=job,resume) with the job's display fields flattened on.
 */
export type ApplicationView = {
    id: string;
    jobId: string;
    resumeId: (string | null);
    stage: Stage;
    version: number;
    createdAt: string;
    flag?: (ApplicationFlag | null);
    contact?: (string | null);
    coachNudge?: (boolean | null);
    resurrected?: (boolean | null);
    outcome?: (Outcome | null);
    outcomeAt?: (string | null);
    outcomeReason?: (string | null);
    outcomeReasons?: (Array<(string)> | null);
    systemReasons?: (Array<(string)> | null);
    submittedSnapshotId?: (string | null);
    searchId?: (string | null);
    job: Job;
    resume: (Resume | null);
    company: string;
    role: string;
    location: string;
    salary: (SalaryPoint | SalaryRange | null);
    match: number;
    source: string;
    resumeName: string;
};

/**
 * Anonymous inline body for ``PUT /projections/{id}/template``.
 */
export type AssignTemplateInput = {
    templateId: string;
};

export type Author = 'user' | 'bot';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_updateSearchCriteria = {
    criteria: SearchCriteria;
};

export type Cadence = 'hourly' | 'salary';

export type CareerHistoryItem = {
    id: string;
    kind: Kind3;
    title: string;
    org?: (string | null);
    bullets: Array<(string)>;
    ordinal: number;
    sourceUploadIds: Array<(string)>;
};

export type Category = 'compensation' | 'motivation' | 'work-authorization' | 'logistics' | 'eeo' | 'other';

export type Classification = 'w2' | 'contract' | '1099';

export type CoachDiff = {
    field: string;
    before: string;
    after: string;
};

export type CoachMessage = {
    id: string;
    author: Author;
    text: string;
    draft?: (string | null);
    draftAttachments?: (Array<DraftAttachment> | null);
    typing?: (boolean | null);
};

/**
 * COA-032 -- reviewed (gate 1) before it is saved (gate 2).
 */
export type CoachProposal = {
    id: string;
    subject: CoachSubject;
    summary: string;
    diff: Array<CoachDiff>;
    status: string;
};

/**
 * COA-031 -- the live "what am I looking at" descriptor.
 */
export type CoachSubject = {
    scope: CoachThreadScope;
    id?: (string | null);
    label: string;
};

export type CoachThread = {
    id: string;
    title: string;
    scope: CoachThreadScope;
    when: string;
    active?: (boolean | null);
};

/**
 * Response shape for ``getCoachThread`` -- the contract defines this as
 * an anonymous inline object (``{thread, messages, context}``), so
 * datamodel-codegen emits no named schema for it. Modeled locally here to
 * keep ``response_model`` typed per the mock route pattern.
 */
export type CoachThreadBundle = {
    thread: CoachThread;
    messages: Array<CoachMessage>;
    context: Array<ContextCard>;
};

/**
 * Note `résumé` with é -- verbatim from source; fixtures depend on the spelling.
 */
export type CoachThreadScope = 'application' | 'résumé' | 'career-history' | 'projection' | 'contact' | 'answer' | 'project' | 'accomplishment' | 'prep' | 'general';

export type Commitment = 'full-time' | 'part-time';

export type Contact = {
    name: string;
    role: string;
    org: string;
    email: string;
    phone: string;
    relationship: string;
    isReference: boolean;
    tags: Array<(string)>;
    links: Array<Link>;
    notes: string;
    id: string;
    updated: string;
    deletedAt?: (string | null);
};

export type ContactDraft = {
    name: string;
    role: string;
    org: string;
    email: string;
    phone: string;
    relationship: string;
    isReference: boolean;
    tags: Array<(string)>;
    links: Array<Link>;
    notes: string;
};

export type ContextCard = {
    label: string;
    body: string;
};

/**
 * D8b consent panel payload, returned before any paid LLM run.
 */
export type CostPreview = {
    items: Array<CostPreviewItem>;
    totalUsd: number;
    capRemainingUsd: number;
    overCap: boolean;
};

export type CostPreviewItem = {
    resumeId: string;
    model: string;
    estCostUsd: number;
};

export type CreateApplicationInput = {
    company: string;
    role: string;
    location: string;
    salary: (SalaryPoint | SalaryRange | null);
    match: number;
    source: string;
    resumeId?: (string | null);
    searchId?: (string | null);
};

/**
 * Anonymous inline body for ``POST /projections``.
 */
export type CreateProjectionInput = {
    name: string;
    targetRole?: (string | null);
    itemIds: Array<(string)>;
    templateId?: (string | null);
    sourceUploadId?: (string | null);
};

export type CreateSearchInput = {
    name: string;
    criteria: SearchCriteria;
};

export type Credential = {
    id: string;
    name: string;
    type: Type;
    issuer: string;
    expiry?: (string | null);
    fileRef: string;
    updated: string;
};

export type DataExportRequest = {
    url: string;
    requestedAt: string;
};

export type DeepMatchResult = {
    jobId: string;
    resumeId: string;
    score: number;
    kind: Kind2;
    strengths: Array<(string)>;
    gaps: Array<(string)>;
    costUsd: number;
    aiRun: AiRunEnvelope;
};

export type DeletionImpact = {
    kind: LibraryKind;
    id: string;
    dependents: Array<Dependent>;
    total: number;
};

export type Dependent = {
    kind: LibraryKind;
    count: number;
    items: Array<Item>;
};

/**
 * Local request-body shape for deriveAccomplishmentFromProject.
 *
 * The contract inlines this object (``{projectId}``) rather than naming a
 * reusable schema, so ``datamodel-codegen`` did not emit a model for it in
 * ``app.schemas``. Defined here rather than editing the generated
 * file.
 */
export type DeriveAccomplishmentFromProjectBody = {
    projectId: string;
};

/**
 * Anonymous inline body for ``POST /applications/{id}/dismiss``.
 */
export type DismissBody = {
    reasons?: (Array<(string)> | null);
};

export type DismissResult = {
    outcome: Outcome1;
};

export type DraftAttachment = {
    name: string;
    kind: Kind4;
};

/**
 * D9b -- parser behavior once the monthly cap is hit.
 */
export type EmailParserFallback = {
    mode: Mode;
    model?: (string | null);
};

/**
 * ADR-006 -- three independent atomic axes.
 */
export type Employment = {
    classification: Classification;
    cadence: Cadence;
    commitment: Commitment;
};

export type ExtensionToken = {
    id: string;
    label: string;
    createdAt: string;
    revokedAt?: (string | null);
};

/**
 * Anonymous inline body for ``POST /resumes/{id}/fork``.
 */
export type ForkResumeInput = {
    jobId: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IntegrationRow = {
    name: string;
    description: string;
    state: State1;
    account?: (string | null);
    lastSync?: (string | null);
};

export type InterviewFormat = 'video' | 'phone' | 'onsite';

/**
 * Anonymous inline body for ``PATCH /applications/{appId}/interviews/{roundId}``.
 *
 * ``extra='forbid'`` implements the TRK-127 allowlist: only date/type/format/
 * status may be sent; any other field -> 422 ``validation_error``.
 */
export type InterviewPatchBody = {
    date?: (string | null);
    type?: (InterviewType | null);
    format?: (InterviewFormat | null);
    status?: (InterviewStatus | null);
};

export type InterviewRound = {
    id: string;
    appId: string;
    date: string;
    type: InterviewType;
    format: InterviewFormat;
    status: InterviewStatus;
};

export type InterviewStatus = 'scheduled' | 'completed' | 'cancelled';

export type InterviewType = 'recruiter-screen' | 'technical' | 'onsite' | 'final';

export type InvoiceRow = {
    date: string;
    description: string;
    amountUsd: number;
};

export type Item = {
    id: string;
    label: string;
};

/**
 * A captured posting -- the canonical resource (ADR-006).
 */
export type Job = {
    id: string;
    company: string;
    title: string;
    location: JobLocation;
    workMode: JobWorkMode;
    employment: Employment;
    compensation: (SalaryPoint | SalaryRange | null);
    seniority?: (string | null);
    source: JobSource;
    isNew?: (boolean | null);
    posted: string;
    summary?: (string | null);
    tags?: (Array<(string)> | null);
    requirements?: (Array<(string)> | null);
    description?: (string | null);
    match?: (JobMatch | null);
};

export type JobCaptureMethod = 'url' | 'jd-text' | 'extension' | 'email-forward';

export type JobInboxItem = {
    jobId?: (string | null);
    company: string;
    role: string;
    location: string;
    salary: (SalaryPoint | SalaryRange | null);
    match: number;
    source: string;
    isNew?: (boolean | null);
    posted: string;
    capturedVia?: (JobCaptureMethod | null);
    capturedAt?: (string | null);
    sourceUrl?: (string | null);
    workMode?: (JobWorkMode | null);
    employmentType?: (string | null);
    seniority?: (string | null);
    summary?: (string | null);
    tags?: (Array<(string)> | null);
    requirements?: (Array<(string)> | null);
    strengths?: (Array<(string)> | null);
    gaps?: (Array<(string)> | null);
    jd?: (string | null);
};

export type JobLocation = {
    raw: string;
    locality?: (string | null);
    region?: (string | null);
    country?: (string | null);
};

export type JobMatch = {
    score: number;
    strengths: Array<(string)>;
    gaps: Array<(string)>;
    kind?: (Kind1 | null);
};

export type JobSource = {
    board: string;
    channel: JobCaptureMethod;
    url?: (string | null);
    capturedAt: string;
};

export type JobWorkMode = 'remote' | 'hybrid' | 'onsite';

/**
 * D8 -- rough = free local heuristic; deep = paid LLM. Absent = rough.
 */
export type Kind1 = 'rough' | 'deep';

export type Kind2 = 'deep';

export type Kind3 = 'experience' | 'education' | 'skill' | 'project' | 'summary';

export type Kind4 = 'resume' | 'cover-letter' | 'file';

export type Kind5 = 'reply' | 'agent' | 'match' | 'cal';

export type LibraryKind = 'contact' | 'accomplishment' | 'answer' | 'project';

export type Link = {
    label: string;
    url: string;
};

export type MarkWonInput = {
    startDate?: (string | null);
    negotiatedComp?: (SalaryPoint | SalaryRange | null);
    whatWorked?: (string | null);
};

export type MarkWonResult = {
    application: ApplicationView;
    undoToken: string;
    undoExpiresAt: string;
    undoWindowSeconds: number;
};

export type MatchGap = {
    severity: Severity;
    text: string;
};

export type MatchReport = {
    resumeId: string;
    jobId: string;
    score: number;
    rubric: Array<MatchRubricRow>;
    gaps: Array<MatchGap>;
    strengths: Array<(string)>;
};

export type MatchRubricRow = {
    label: string;
    score: number;
    note: string;
};

export type Message = {
    message: string;
};

export type Mode = 'deterministic' | 'cheap-model';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Notification = {
    id: string;
    kind: Kind5;
    title: string;
    message: string;
    actor: string;
    unread?: (boolean | null);
};

export type NotifPref = {
    id: string;
    category: string;
    emailEnabled: boolean;
    inAppEnabled: boolean;
    emailLocked?: (boolean | null);
};

/**
 * ORI-009 archive bucket; present only on archived entries.
 */
export type Outcome = 'won' | 'rejected' | 'withdrawn';

/**
 * removed = pre-commit delete; withdrew = post-APPLIED archive.
 */
export type Outcome1 = 'removed' | 'withdrew';

/**
 * Request body for ``patchAgent`` -- contract defines this inline (no
 * named schema), so it is modeled locally here rather than in the generated
 * ``models.py``.
 */
export type PatchAgentInput = {
    state?: (AgentState | null);
    live?: (boolean | null);
};

/**
 * Request body for ``patchAgentTrustTier`` -- inline in the contract, no
 * named schema; modeled locally like ``PatchAgentInput`` above.
 */
export type PatchAgentTrustTierInput = {
    targetTier: AgentTrustTier;
};

/**
 * Anonymous inline body for ``PATCH /resumes/{id}``.
 *
 * Collapses 3 mock mutations (renameResume/saveResumeBody/
 * patchResumeScoring) onto one PATCH; every field optional, only
 * client-sent fields are applied (exclude_unset merge in the route).
 */
export type PatchResumeBody = {
    name?: (string | null);
    body?: (string | null);
    scoringEnabled?: (boolean | null);
};

export type Plan = {
    name: string;
    priceUsd: number;
    description: string;
    nextCharge: string;
};

/**
 * Inline requestBody for ``POST /jobs/{id}/preview-deep-score``.
 */
export type PreviewDeepScoreBody = {
    resumeIds: Array<(string)>;
};

export type PreviewKind = 'single-column' | 'two-column' | 'compact' | 'modern';

/**
 * Toggle STATE is data; the title/description copy is client-owned, keyed off `key`.
 */
export type PrivacyToggle = {
    key: string;
    on: boolean;
};

export type Profile = {
    name: string;
    email: string;
    phone: string;
    timezone: string;
    currentRole: string;
    targetTitles: Array<(string)>;
    compFloorUsd: number;
};

export type Project = {
    title: string;
    employer: string;
    body: string;
    tags: Array<(string)>;
    id: string;
    updated: string;
    deletedAt?: (string | null);
};

/**
 * PRJ-001 -- a per-employer brain-dump / evidence reservoir.
 */
export type ProjectDraft = {
    title: string;
    employer: string;
    body: string;
    tags: Array<(string)>;
};

export type ProviderRow = {
    provider: string;
    model: string;
    state: State2;
    balanceUsd?: (number | null);
    error?: (string | null);
};

/**
 * Machine tokens; client maps to display copy.
 */
export type RemotePolicy = 'remote-ok' | 'hybrid-ok' | 'required';

/**
 * Anonymous inline body for ``POST /exports``.
 */
export type RenderExportInput = {
    projectionId: string;
};

/**
 * In the resume-lifecycle model (RES-034, ADR-007/008) a non-FORMAT Resume IS a projection -- a curated selection over career history.
 */
export type Resume = {
    id: string;
    name: string;
    subtitle: string;
    version: string;
    usedIn: number;
    updated: string;
    tag: ResumeTag;
    match?: (number | null);
    body?: (string | null);
    sourceUploadId?: (string | null);
    templateId?: (string | null);
    targetRole?: (string | null);
    scoringEnabled?: (boolean | null);
};

export type ResumeExport = {
    id: string;
    projectionId: string;
    templateId: string;
    templateVersion: string;
    filename: string;
    generatedAt: string;
    regenerable: boolean;
};

/**
 * D10 immutable copy of the resume captured at APPLIED.
 */
export type ResumeSnapshot = {
    id: string;
    applicationId: string;
    resumeId: string;
    name: string;
    body: string;
    templateVersion: string;
    capturedAt: string;
};

export type ResumeTag = 'MASTER' | 'DEFAULT' | 'VARIANT' | 'TAILORED' | 'DRAFT' | 'FORMAT';

export type ResumeTemplate = {
    id: string;
    name: string;
    previewKind: PreviewKind;
    description: string;
};

export type ResumeUpload = {
    id: string;
    filename: string;
    uploadedAt: string;
    parsed: boolean;
    sizeBytes: number;
};

export type ReviewQueueItem = {
    id: string;
    agentId: string;
    message: string;
    time: string;
};

/**
 * Per-task provider routing (label/value were generic display pairs; now semantic).
 */
export type RoutingRow = {
    task: string;
    model: string;
};

/**
 * Inline requestBody for ``POST /jobs/{id}/deep-score``.
 */
export type RunDeepScoreBody = {
    resumeId: string;
};

export type SalaryPoint = {
    value: number;
    extra: Array<(string)>;
};

export type SalaryRange = {
    min: number;
    max: number;
    extra: Array<(string)>;
};

export type Search = {
    id: string;
    name: string;
    state?: (State | null);
    criteria: SearchCriteria;
    jobsInInbox: number;
    activeApplications: number;
    shortlisted: number;
    offers: number;
    spendMoUsd: number;
};

export type SearchCriteria = {
    titlesInclude: Array<(string)>;
    titlesExclude: Array<(string)>;
    locations: Array<(string)>;
    remotePolicy: RemotePolicy;
    maxCommuteMin: number;
    baseFloorUsd: number;
    baseCeilingUsd: number;
    yearsExperienceMin?: (number | null);
    yearsExperienceMax?: (number | null);
    scoringResumeIds?: (Array<(string)> | null);
};

export type Settings = {
    profile: Profile;
    integrations: Array<IntegrationRow>;
    providers: Array<ProviderRow>;
    routing: Array<RoutingRow>;
    usage: Array<UsageRow>;
    monthSpendUsd: number;
    monthlyCapUsd: number;
    privacy: Array<PrivacyToggle>;
    privacyLastUpdated: string;
    plan: Plan;
    invoices: Array<InvoiceRow>;
    notifPrefs: Array<NotifPref>;
    extensionTokens: Array<ExtensionToken>;
    emailParserFallback: EmailParserFallback;
};

export type Severity = 'high' | 'medium' | 'low';

export type ShortlistEntry = {
    id: string;
    jobId?: (string | null);
    company: string;
    role: string;
    location: string;
    salary: (SalaryPoint | SalaryRange | null);
    match: number;
    saved: string;
    source: Source;
    why?: (string | null);
    stale?: (boolean | null);
};

export type Source = 'you';

/**
 * ACC-002 -- set when distilled from a Project (snapshot + backlink), else null.
 */
export type Source1 = {
    projectId: string;
};

/**
 * Settled application-stage taxonomy (state-machines.md#application-stages is normative over the mock's coarser 8-value enum). Lowercase wire values; multiword stages use snake_case.
 */
export type Stage = 'saved' | 'drafting' | 'applied' | 'screening' | 'interview' | 'offer' | 'won' | 'rejected' | 'ghosted' | 'withdrew' | 'dismissed' | 'offer_rescinded';

/**
 * One appended, immutable row of an application's stage-transition audit log. Corrections are compensating transitions referencing the prior row.
 */
export type StageTransition = {
    id: string;
    applicationId: string;
    fromStage?: (Stage | null);
    toStage: Stage;
    source: TransitionSource;
    reason?: (string | null);
    reasons?: (Array<(string)> | null);
    resumeId?: (string | null);
    createdAt: string;
};

/**
 * Defaults to active when absent. No pause/activate mutation is frozen (see DECISIONS-NEEDED.md).
 */
export type State = 'active' | 'paused';

export type State1 = 'connected' | 'not-connected' | 'auto';

export type State2 = 'connected' | 'not-connected' | 'error';

export type TimelineEvent = {
    id: string;
    time: string;
    who: string;
    message: string;
    actor?: (Actor | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransitionInput = {
    targetStage: Stage;
    expectedVersion: number;
    source?: (TransitionSource | null);
    reason?: (string | null);
    reasons?: (Array<(string)> | null);
    resumeId?: (string | null);
};

export type TransitionResult = {
    application: ApplicationView;
    transition: StageTransition;
};

/**
 * Who/what drove the transition (aligned with the settled machine sources).
 */
export type TransitionSource = 'user' | 'user_correction' | 'user_reactivation' | 'system';

export type TrashEntry = {
    kind: LibraryKind;
    id: string;
    label: string;
    deletedAt: string;
};

/**
 * One rung of the ladder. label/blurb were UI copy (client-owned).
 */
export type TrustTierRung = {
    tier: AgentTrustTier;
};

export type Type = 'license' | 'certification' | 'transcript' | 'portfolio' | 'other';

/**
 * Anonymous inline body for ``POST /applications/{id}/undo-mark-won``.
 */
export type UndoMarkWonBody = {
    undoToken: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UsageAggregate = {
    monthSpendUsd: number;
    monthlyCapUsd: number;
    tokensIn: number;
    tokensOut: number;
    avgPerSessionUsd: number;
};

export type UsageRow = {
    service: string;
    model: string;
    count: number;
    tokens: number;
    costUsd: number;
};

export type User = {
    name: string;
    email: string;
    initials: string;
    city: string;
    current: string;
    years: number;
    comp_floor: number;
    target_titles: Array<(string)>;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    initials?: (string | null);
    city?: (string | null);
    current?: (string | null);
    years?: (number | null);
    comp_floor?: (number | null);
    target_titles?: Array<(string)>;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    initials?: (string | null);
    city?: (string | null);
    current?: (string | null);
    years?: (number | null);
    comp_floor?: (number | null);
    target_titles?: Array<(string)>;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type RequestDataExportResponse = (DataExportRequest);

export type DeleteAccountResponse = (AccountDeletionResult);

export type GetAgentsResponse = (Array<Agent>);

export type GetAgentLogData = {
    agentId?: (string | null);
    kind?: (AgentLogKind | null);
};

export type GetAgentLogResponse = (Array<AgentLogEntry>);

export type GetReviewQueueResponse = (Array<ReviewQueueItem>);

export type GetAgentData = {
    id: string;
};

export type GetAgentResponse = (Agent);

export type PatchAgentData = {
    id: string;
    requestBody: PatchAgentInput;
};

export type PatchAgentResponse = (Agent);

export type GetAgentPermissionsData = {
    id: string;
};

export type GetAgentPermissionsResponse = (Array<AgentPermission>);

export type GetAgentTrustTierData = {
    id: string;
};

export type GetAgentTrustTierResponse = (AgentTrustTierView);

export type PatchAgentTrustTierData = {
    id: string;
    requestBody: PatchAgentTrustTierInput;
};

export type PatchAgentTrustTierResponse = (AgentTrustTierUpdate);

export type ApproveAgentActionData = {
    id: string;
};

export type ApproveAgentActionResponse = (void);

export type RejectAgentActionData = {
    id: string;
};

export type RejectAgentActionResponse = (void);

export type GetApplicationsData = {
    searchId?: (string | null);
};

export type GetApplicationsResponse = (Array<ApplicationView>);

export type CreateApplicationData = {
    requestBody: CreateApplicationInput;
};

export type CreateApplicationResponse = (ApplicationView);

export type GetApplicationData = {
    id: string;
};

export type GetApplicationResponse = (ApplicationView);

export type TransitionApplicationData = {
    id: string;
    requestBody: TransitionInput;
};

export type TransitionApplicationResponse = (TransitionResult);

export type GetResumeSnapshotData = {
    id: string;
};

export type GetResumeSnapshotResponse = (ResumeSnapshot);

export type MarkWonData = {
    id: string;
    requestBody?: (MarkWonInput | null);
};

export type MarkWonResponse = (MarkWonResult);

export type UndoMarkWonData = {
    id: string;
    requestBody: UndoMarkWonBody;
};

export type UndoMarkWonResponse = (ApplicationView);

export type ReactivateApplicationData = {
    id: string;
};

export type ReactivateApplicationResponse = (ApplicationView);

export type DismissApplicationData = {
    id: string;
    requestBody?: (DismissBody | null);
};

export type DismissApplicationResponse = (DismissResult);

export type GetApplicationTimelineData = {
    id: string;
};

export type GetApplicationTimelineResponse = (Array<TimelineEvent>);

export type GetArchiveData = {
    kind: string;
};

export type GetArchiveResponse = (Array<ApplicationView>);

export type GetArchiveCountsResponse = ({
    [key: string]: (number);
});

export type GetCoachThreadsResponse = (Array<CoachThread>);

export type GetCoachThreadData = {
    id: string;
};

export type GetCoachThreadResponse = (CoachThreadBundle);

export type ProposeCoachEditData = {
    requestBody: CoachSubject;
};

export type ProposeCoachEditResponse = (CoachProposal);

export type SaveCoachProposalData = {
    id: string;
    requestBody: CoachProposal;
};

export type SaveCoachProposalResponse = (TimelineEvent);

export type GetInterviewRoundsData = {
    id: string;
};

export type GetInterviewRoundsResponse = (Array<InterviewRound>);

export type PatchInterviewRoundData = {
    appId: string;
    requestBody: InterviewPatchBody;
    roundId: string;
};

export type PatchInterviewRoundResponse = (InterviewRound);

export type GetJobsResponse = (Array<Job>);

export type GetJobsInboxData = {
    searchId?: (string | null);
};

export type GetJobsInboxResponse = (Array<JobInboxItem>);

export type GetJobData = {
    id: string;
};

export type GetJobResponse = (Job);

export type GetContactsResponse = (Array<Contact>);

export type CreateContactData = {
    requestBody: ContactDraft;
};

export type CreateContactResponse = (Contact);

export type GetContactData = {
    id: string;
};

export type GetContactResponse = (Contact);

export type UpdateContactData = {
    id: string;
    requestBody: ContactDraft;
};

export type UpdateContactResponse = (Contact);

export type DeleteContactData = {
    id: string;
};

export type DeleteContactResponse = (void);

export type GetAccomplishmentsResponse = (Array<Accomplishment>);

export type CreateAccomplishmentData = {
    requestBody: AccomplishmentDraft;
};

export type CreateAccomplishmentResponse = (Accomplishment);

export type UpdateAccomplishmentData = {
    id: string;
    requestBody: AccomplishmentDraft;
};

export type UpdateAccomplishmentResponse = (Accomplishment);

export type DeleteAccomplishmentData = {
    id: string;
};

export type DeleteAccomplishmentResponse = (void);

export type DeriveAccomplishmentFromProjectData = {
    requestBody: DeriveAccomplishmentFromProjectBody;
};

export type DeriveAccomplishmentFromProjectResponse = (AccomplishmentDeriveResult);

export type GetAnswersResponse = (Array<Answer>);

export type CreateAnswerData = {
    requestBody: AnswerDraft;
};

export type CreateAnswerResponse = (Answer);

export type UpdateAnswerData = {
    id: string;
    requestBody: AnswerDraft;
};

export type UpdateAnswerResponse = (Answer);

export type DeleteAnswerData = {
    id: string;
};

export type DeleteAnswerResponse = (void);

export type GetProjectsResponse = (Array<Project>);

export type CreateProjectData = {
    requestBody: ProjectDraft;
};

export type CreateProjectResponse = (Project);

export type UpdateProjectData = {
    id: string;
    requestBody: ProjectDraft;
};

export type UpdateProjectResponse = (Project);

export type DeleteProjectData = {
    id: string;
};

export type DeleteProjectResponse = (void);

export type GetCredentialsResponse = (Array<Credential>);

export type GetTrashResponse = (Array<TrashEntry>);

export type RestoreLibraryItemData = {
    id: string;
    kind: LibraryKind;
};

export type RestoreLibraryItemResponse = (void);

export type PurgeLibraryItemData = {
    id: string;
    kind: LibraryKind;
};

export type PurgeLibraryItemResponse = (void);

export type GetDeletionImpactData = {
    id: string;
    kind: LibraryKind;
};

export type GetDeletionImpactResponse = (DeletionImpact);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PreviewDeepMatchScoreData = {
    id: string;
    requestBody: PreviewDeepScoreBody;
};

export type PreviewDeepMatchScoreResponse = (CostPreview);

export type RunDeepMatchScoreData = {
    id: string;
    requestBody: RunDeepScoreBody;
};

export type RunDeepMatchScoreResponse = (DeepMatchResult);

export type GetMatchReportData = {
    jobId: string;
    resumeId: string;
};

export type GetMatchReportResponse = (MatchReport);

export type GetNotificationsResponse = (Array<Notification>);

export type MarkNotificationReadData = {
    id: string;
};

export type MarkNotificationReadResponse = (Notification);

export type MarkAllNotificationsReadResponse = (Array<Notification>);

export type GetResumeUploadsResponse = (Array<ResumeUpload>);

export type GetCareerHistoryResponse = (Array<CareerHistoryItem>);

export type GetResumeTemplatesResponse = (Array<ResumeTemplate>);

export type GetResumeExportsResponse = (Array<ResumeExport>);

export type GetProjectionsResponse = (Array<Resume>);

export type CreateProjectionData = {
    requestBody: CreateProjectionInput;
};

export type CreateProjectionResponse = (Resume);

export type AssignTemplateData = {
    id: string;
    requestBody: AssignTemplateInput;
};

export type AssignTemplateResponse = (Resume);

export type RenderExportData = {
    requestBody: RenderExportInput;
};

export type RenderExportResponse = (ResumeExport);

export type RegenerateExportData = {
    id: string;
};

export type RegenerateExportResponse = (ResumeExport);

export type GetResumesResponse = (Array<Resume>);

export type CreateResumeResponse = (Resume);

export type GetResumeData = {
    id: string;
};

export type GetResumeResponse = (Resume);

export type PatchResumeData = {
    id: string;
    requestBody: PatchResumeBody;
};

export type PatchResumeResponse = (Resume);

export type DeleteResumeData = {
    id: string;
};

export type DeleteResumeResponse = (void);

export type DuplicateResumeData = {
    id: string;
};

export type DuplicateResumeResponse = (Resume);

export type SetDefaultResumeData = {
    id: string;
};

export type SetDefaultResumeResponse = (Array<Resume>);

export type ForkResumeAsDraftData = {
    id: string;
    requestBody: ForkResumeInput;
};

export type ForkResumeAsDraftResponse = (Resume);

export type GetSearchesResponse = (Array<Search>);

export type CreateSearchData = {
    requestBody: CreateSearchInput;
};

export type CreateSearchResponse = (Search);

export type GetSearchData = {
    id: string;
};

export type GetSearchResponse = (Search);

export type UpdateSearchCriteriaData = {
    id: string;
    requestBody: Body_updateSearchCriteria;
};

export type UpdateSearchCriteriaResponse = (Search);

export type GetSettingsResponse = (Settings);

export type GetUsageAggregateResponse = (UsageAggregate);

export type GetShortlistData = {
    searchId?: (string | null);
};

export type GetShortlistResponse = (Array<ShortlistEntry>);

export type AddToShortlistData = {
    requestBody: AddToShortlistBody;
};

export type AddToShortlistResponse = (ShortlistEntry);

export type DismissFromShortlistData = {
    id: string;
};

export type DismissFromShortlistResponse = (void);

export type GetCurrentUserResponse = (User);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);