// This file is auto-generated by @hey-api/openapi-ts

export type Accomplishment = AccomplishmentDraft & {
    id: string;
    usedIn: number;
    updated: string;
    deletedAt?: string;
};

/**
 * Response of deriveAccomplishmentFromProject (AI op); the accomplishment plus its run telemetry.
 */
export type AccomplishmentDeriveResult = {
    accomplishment: Accomplishment;
    aiRun: AiRunEnvelope;
};

export type AccomplishmentDraft = {
    title: string;
    summary: string;
    tags: Array<(string)>;
    /**
     * ACC-002 -- set when distilled from a Project (snapshot + backlink), else null.
     */
    source: ({
    projectId: string;
} | null);
};

export type Agent = {
    id: string;
    name: string;
    state: AgentState;
    lastActivity: string;
    actions: number;
    /**
     * Agent's month-to-date cost
     */
    costUsd: number;
    description: string;
    live?: boolean;
    trustTier?: AgentTrustTier;
};

export type AgentLogEntry = {
    time: string;
    agentId: string;
    kind: AgentLogKind;
    message: string;
    /**
     * Opaque cross-reference to the acted-upon entity.
     */
    ref: string;
};

export type AgentLogKind = 'auto' | 'await' | 'success' | 'skipped';

export type AgentPermission = {
    permission: string;
    granted: boolean;
    requiredTier?: AgentTrustTier;
};

export type AgentState = 'running' | 'demand' | 'paused' | 'error';

export type AgentTrustTier = 'observe' | 'suggest' | 'act-with-approval' | 'autonomous';

export type AgentTrustTierUpdate = {
    agentId: string;
    currentTier: AgentTrustTier;
    /**
     * State model DEFERRED (founder ruled 2026-07-04, DECISIONS-NEEDED
     */
    status: string;
    message: string;
};

export type AgentTrustTierView = {
    agentId: string;
    currentTier: AgentTrustTier;
    unlockedAt?: string;
    ladder: Array<TrustTierRung>;
};

/**
 * Telemetry envelope embedded (as `aiRun`) in every AI operation's response. Execution is synchronous; `status` is terminal (`succeeded`/`failed`/`cancelled`) by the time the response returns.
 *
 */
export type AiRunEnvelope = {
    /**
     * e.g. claude_cli
     */
    provider: string;
    model: string;
    status: AiRunStatus;
    startedAt?: (string) | null;
    finishedAt?: (string) | null;
    durationMs?: (number) | null;
    estimatedCostUsd: number;
    actualCostUsd?: (number) | null;
    /**
     * True iff produced by the FakeProvider (never satisfies evidence/approval).
     */
    synthetic: boolean;
};

/**
 * Wire status is always terminal (synchronous execution). The full 5-state lifecycle (queued/running/...) is a server-side telemetry concern on the persisted run record, not exposed on the response.
 *
 */
export type AiRunStatus = 'succeeded' | 'failed' | 'cancelled';

export type Answer = AnswerDraft & {
    id: string;
    updated: string;
    deletedAt?: string;
};

export type AnswerDraft = {
    question: string;
    body: string;
    category: 'compensation' | 'motivation' | 'work-authorization' | 'logistics' | 'eeo' | 'other';
    tags: Array<(string)>;
};

export type category = 'compensation' | 'motivation' | 'work-authorization' | 'logistics' | 'eeo' | 'other';

/**
 * Stored application record (ADR-006 stage 3, fully normalized).
 */
export type Application = {
    id: string;
    /**
     * FK -> Job.id.
     */
    jobId: string;
    /**
     * FK -> Resume.id; null when none yet.
     */
    resumeId: (string) | null;
    stage: Stage;
    /**
     * Optimistic-concurrency counter; bumped on every transition (see TransitionInput.expectedVersion).
     */
    version: number;
    /**
     * Replaces the mock's relative `days`; the client derives age.
     */
    createdAt: string;
    flag?: ApplicationFlag;
    contact?: string;
    coachNudge?: boolean;
    resurrected?: boolean;
    /**
     * ORI-009 archive bucket; present only on archived entries.
     */
    outcome?: 'won' | 'rejected' | 'withdrawn';
    outcomeAt?: string;
    outcomeReason?: string;
    /**
     * D16 user-chosen reason chips (max 8).
     */
    outcomeReasons?: Array<(string)>;
    /**
     * D16 system-applied chips -- separate tier, not counted in the user 8.
     */
    systemReasons?: Array<(string)>;
    /**
     * D10 FK -> ResumeSnapshot.id, set at APPLIED.
     */
    submittedSnapshotId?: string;
    /**
     * D15 FK -> Search.id (non-null in practice).
     */
    searchId?: string;
};

/**
 * ORI-009 archive bucket; present only on archived entries.
 */
export type outcome = 'won' | 'rejected' | 'withdrawn';

export type ApplicationFlag = 'stale' | 'offer';

/**
 * Read model -- an Application joined with its Job and Resume (equivalent of GET /applications/{id}?expand=job,resume) with the job's display fields flattened on.
 *
 */
export type ApplicationView = Application & {
    job: Job;
    resume: (Resume | null);
    company: string;
    role: string;
    location: string;
    salary: (Salary | null);
    match: number;
    /**
     * Origin ATS/board (greenhouse
     */
    source: string;
    resumeName: string;
};

export type CareerHistoryItem = {
    id: string;
    kind: 'experience' | 'education' | 'skill' | 'project' | 'summary';
    title: string;
    org?: string;
    bullets: Array<(string)>;
    ordinal: number;
    /**
     * RES-038 merge provenance.
     */
    sourceUploadIds: Array<(string)>;
};

export type kind = 'experience' | 'education' | 'skill' | 'project' | 'summary';

export type CoachDiff = {
    field: string;
    before: string;
    after: string;
};

export type CoachMessage = {
    id: string;
    author: 'user' | 'bot';
    text: string;
    draft?: string;
    /**
     * COA-024 -- items to attach when sending from the user's OWN email client.
     */
    draftAttachments?: Array<{
        name: string;
        kind: 'resume' | 'cover-letter' | 'file';
    }>;
    typing?: boolean;
};

export type author = 'user' | 'bot';

/**
 * COA-032 -- reviewed (gate 1) before it is saved (gate 2).
 */
export type CoachProposal = {
    id: string;
    subject: CoachSubject;
    summary: string;
    diff: Array<CoachDiff>;
    /**
     * State model DEFERRED (founder ruled 2026-07-04, DECISIONS-NEEDED
     */
    status: string;
};

/**
 * COA-031 -- the live "what am I looking at" descriptor.
 */
export type CoachSubject = {
    scope: CoachThreadScope;
    id?: string;
    label: string;
};

export type CoachThread = {
    id: string;
    /**
     * Thread title (data
     */
    title: string;
    scope: CoachThreadScope;
    when: string;
    active?: boolean;
};

/**
 * Note `résumé` with é -- verbatim from source; fixtures depend on the spelling.
 */
export type CoachThreadScope = 'application' | 'résumé' | 'career-history' | 'projection' | 'contact' | 'answer' | 'project' | 'accomplishment' | 'prep' | 'general';

export type Contact = ContactDraft & {
    id: string;
    updated: string;
    /**
     * D24 soft-delete marker; set = in the trash.
     */
    deletedAt?: string;
};

export type ContactDraft = {
    name: string;
    role: string;
    org: string;
    email: string;
    phone: string;
    relationship: string;
    /**
     * References are a tagged role (CON-002).
     */
    isReference: boolean;
    tags: Array<(string)>;
    links: Array<{
        label: string;
        url: string;
    }>;
    notes: string;
};

export type ContextCard = {
    label: string;
    body: string;
};

/**
 * D8b consent panel payload, returned before any paid LLM run.
 */
export type CostPreview = {
    items: Array<CostPreviewItem>;
    totalUsd: number;
    capRemainingUsd: number;
    overCap: boolean;
};

export type CostPreviewItem = {
    /**
     * The resume this line prices (label was UI copy).
     */
    resumeId: string;
    model: string;
    estCostUsd: number;
};

export type CreateApplicationInput = {
    company: string;
    role: string;
    location: string;
    salary: (Salary | null);
    match: number;
    source: string;
    /**
     * Selected resume; null when none yet.
     */
    resumeId?: (string) | null;
    /**
     * D15 target saved search; defaults to last-used / auto-created "My jobs".
     */
    searchId?: string;
};

export type CreateSearchInput = {
    name: string;
    /**
     * Partial criteria; unset fields take blank defaults.
     */
    criteria: SearchCriteria;
};

export type Credential = {
    id: string;
    name: string;
    type: 'license' | 'certification' | 'transcript' | 'portfolio' | 'other';
    issuer: string;
    expiry?: string;
    fileRef: string;
    updated: string;
};

export type type = 'license' | 'certification' | 'transcript' | 'portfolio' | 'other';

export type DataExportRequest = {
    url: string;
    requestedAt: string;
};

export type DeepMatchResult = {
    jobId: string;
    resumeId: string;
    score: number;
    kind: 'deep';
    strengths: Array<(string)>;
    gaps: Array<(string)>;
    costUsd: number;
    aiRun: AiRunEnvelope;
};

export type kind2 = 'deep';

export type DeletionImpact = {
    kind: LibraryKind;
    id: string;
    dependents: Array<{
        kind: LibraryKind;
        count: number;
        items: Array<{
            id: string;
            label: string;
        }>;
    }>;
    total: number;
};

export type DismissResult = {
    /**
     * removed = pre-commit delete; withdrew = post-APPLIED archive.
     */
    outcome: 'removed' | 'withdrew';
};

/**
 * removed = pre-commit delete; withdrew = post-APPLIED archive.
 */
export type outcome2 = 'removed' | 'withdrew';

/**
 * D9b -- parser behavior once the monthly cap is hit.
 */
export type EmailParserFallback = {
    mode: 'deterministic' | 'cheap-model';
    /**
     * Cheap model id, present when mode = cheap-model.
     */
    model?: string;
};

export type mode = 'deterministic' | 'cheap-model';

/**
 * ADR-006 -- three independent atomic axes.
 */
export type Employment = {
    classification: 'w2' | 'contract' | '1099';
    cadence: 'hourly' | 'salary';
    commitment: 'full-time' | 'part-time';
};

export type classification = 'w2' | 'contract' | '1099';

export type cadence = 'hourly' | 'salary';

export type commitment = 'full-time' | 'part-time';

export type Error = {
    kind: 'not_found' | 'unauthorized' | 'validation_error' | 'conflict' | 'cap_reached' | 'undo_window_expired' | 'invalid_transition' | 'rate_limited' | 'provider_unavailable';
    path: string;
    message?: string;
};

export type kind3 = 'not_found' | 'unauthorized' | 'validation_error' | 'conflict' | 'cap_reached' | 'undo_window_expired' | 'invalid_transition' | 'rate_limited' | 'provider_unavailable';

export type ExtensionToken = {
    id: string;
    label: string;
    createdAt: string;
    revokedAt?: string;
};

export type IntegrationRow = {
    name: string;
    description: string;
    state: 'connected' | 'not-connected' | 'auto';
    account?: string;
    lastSync?: string;
};

export type state = 'connected' | 'not-connected' | 'auto';

export type InterviewFormat = 'video' | 'phone' | 'onsite';

export type InterviewRound = {
    id: string;
    appId: string;
    date: string;
    type: InterviewType;
    format: InterviewFormat;
    status: InterviewStatus;
};

export type InterviewStatus = 'scheduled' | 'completed' | 'cancelled';

export type InterviewType = 'recruiter-screen' | 'technical' | 'onsite' | 'final';

export type InvoiceRow = {
    date: string;
    description: string;
    amountUsd: number;
};

/**
 * A captured posting -- the canonical resource (ADR-006).
 */
export type Job = {
    id: string;
    company: string;
    title: string;
    location: JobLocation;
    workMode: JobWorkMode;
    employment: Employment;
    compensation: (Salary | null);
    seniority?: string;
    source: JobSource;
    isNew?: boolean;
    posted: string;
    summary?: string;
    tags?: Array<(string)>;
    requirements?: Array<(string)>;
    /**
     * Verbatim JD text.
     */
    description?: string;
    match?: JobMatch;
};

export type JobCaptureMethod = 'url' | 'jd-text' | 'extension' | 'email-forward';

export type JobInboxItem = {
    jobId?: string;
    company: string;
    role: string;
    location: string;
    salary: (Salary | null);
    match: number;
    /**
     * Origin board (greenhouse
     */
    source: string;
    isNew?: boolean;
    posted: string;
    capturedVia?: JobCaptureMethod;
    capturedAt?: string;
    sourceUrl?: string;
    workMode?: JobWorkMode;
    employmentType?: string;
    seniority?: string;
    summary?: string;
    tags?: Array<(string)>;
    requirements?: Array<(string)>;
    strengths?: Array<(string)>;
    gaps?: Array<(string)>;
    /**
     * Raw JD text
     */
    jd?: string;
};

export type JobLocation = {
    raw: string;
    locality?: string;
    region?: string;
    country?: string;
};

export type JobMatch = {
    score: number;
    strengths: Array<(string)>;
    gaps: Array<(string)>;
    /**
     * D8 -- rough = free local heuristic; deep = paid LLM. Absent = rough.
     */
    kind?: 'rough' | 'deep';
};

/**
 * D8 -- rough = free local heuristic; deep = paid LLM. Absent = rough.
 */
export type kind4 = 'rough' | 'deep';

export type JobSource = {
    board: string;
    channel: JobCaptureMethod;
    url?: string;
    capturedAt: string;
};

export type JobWorkMode = 'remote' | 'hybrid' | 'onsite';

export type LibraryKind = 'contact' | 'accomplishment' | 'answer' | 'project';

export type MarkWonInput = {
    startDate?: string;
    /**
     * Negotiated compensation; structured Salary carries qualifiers (equity, sign-on) via SalaryPoint.extra.
     */
    negotiatedComp?: (Salary | null);
    whatWorked?: string;
};

export type MarkWonResult = {
    application: ApplicationView;
    undoToken: string;
    undoExpiresAt: string;
    /**
     * 300 in the mock.
     */
    undoWindowSeconds: number;
};

export type MatchGap = {
    severity: 'high' | 'medium' | 'low';
    text: string;
};

export type severity = 'high' | 'medium' | 'low';

export type MatchReport = {
    resumeId: string;
    jobId: string;
    score: number;
    rubric: Array<MatchRubricRow>;
    gaps: Array<MatchGap>;
    strengths: Array<(string)>;
};

export type MatchRubricRow = {
    label: string;
    score: number;
    note: string;
};

export type Notification = {
    id: string;
    kind: 'reply' | 'agent' | 'match' | 'cal';
    title: string;
    message: string;
    actor: string;
    unread?: boolean;
};

export type kind5 = 'reply' | 'agent' | 'match' | 'cal';

export type NotifPref = {
    id: string;
    /**
     * Category key (data; client owns the consequence copy).
     */
    category: string;
    emailEnabled: boolean;
    inAppEnabled: boolean;
    emailLocked?: boolean;
};

/**
 * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
 *
 */
export type Parameterid = string;

export type ParameterlibraryKind = LibraryKind;

/**
 * Toggle STATE is data; the title/description copy is client-owned, keyed off `key`.
 *
 */
export type PrivacyToggle = {
    /**
     * Stable toggle key the client maps to copy.
     */
    key: string;
    on: boolean;
};

export type Project = ProjectDraft & {
    id: string;
    updated: string;
    deletedAt?: string;
};

/**
 * PRJ-001 -- a per-employer brain-dump / evidence reservoir.
 */
export type ProjectDraft = {
    title: string;
    employer: string;
    body: string;
    tags: Array<(string)>;
};

export type ProviderRow = {
    provider: string;
    model: string;
    state: 'connected' | 'not-connected' | 'error';
    /**
     * Prepaid provider balance
     */
    balanceUsd?: number;
    error?: string;
};

export type state2 = 'connected' | 'not-connected' | 'error';

/**
 * In the resume-lifecycle model (RES-034, ADR-007/008) a non-FORMAT Resume IS a projection -- a curated selection over career history.
 *
 */
export type Resume = {
    id: string;
    name: string;
    /**
     * User-visible resume descriptor (data
     */
    subtitle: string;
    version: string;
    usedIn: number;
    updated: string;
    tag: ResumeTag;
    match?: number;
    body?: string;
    /**
     * RES-034 upload provenance.
     */
    sourceUploadId?: string;
    /**
     * TPL-002 render template.
     */
    templateId?: string;
    targetRole?: string;
    /**
     * D21 -- participates in match scoring; default ON, MASTER-only.
     */
    scoringEnabled?: boolean;
};

export type ResumeExport = {
    id: string;
    projectionId: string;
    templateId: string;
    /**
     * D17 -- frozen per export.
     */
    templateVersion: string;
    filename: string;
    generatedAt: string;
    regenerable: boolean;
};

/**
 * D10 immutable copy of the resume captured at APPLIED.
 */
export type ResumeSnapshot = {
    id: string;
    applicationId: string;
    resumeId: string;
    name: string;
    body: string;
    /**
     * D17 provenance.
     */
    templateVersion: string;
    capturedAt: string;
};

export type ResumeTag = 'MASTER' | 'DEFAULT' | 'VARIANT' | 'TAILORED' | 'DRAFT' | 'FORMAT';

export type ResumeTemplate = {
    id: string;
    name: string;
    previewKind: 'single-column' | 'two-column' | 'compact' | 'modern';
    description: string;
};

export type previewKind = 'single-column' | 'two-column' | 'compact' | 'modern';

export type ResumeUpload = {
    id: string;
    filename: string;
    uploadedAt: string;
    parsed: boolean;
    sizeBytes: number;
};

export type ReviewQueueItem = {
    /**
     * Queue entry id (approve/reject by /agents/review-queue/{id}).
     */
    id: string;
    agentId: string;
    message: string;
    time: string;
};

/**
 * Per-task provider routing (label/value were generic display pairs; now semantic).
 */
export type RoutingRow = {
    /**
     * Task key
     */
    task: string;
    /**
     * Model routed to that task.
     */
    model: string;
};

/**
 * Structured compensation; null on the wire means undisclosed.
 */
export type Salary = SalaryPoint | SalaryRange;

export type SalaryPoint = {
    /**
     * Full dollars.
     */
    value: number;
    extra: Array<(string)>;
};

export type SalaryRange = {
    /**
     * Full dollars.
     */
    min: number;
    /**
     * Full dollars.
     */
    max: number;
    extra: Array<(string)>;
};

export type Search = {
    id: string;
    name: string;
    /**
     * Defaults to active when absent. No pause/activate mutation is frozen (see DECISIONS-NEEDED.md).
     */
    state?: 'active' | 'paused';
    criteria: SearchCriteria;
    jobsInInbox: number;
    activeApplications: number;
    shortlisted: number;
    offers: number;
    /**
     * Month-to-date spend for this search
     */
    spendMoUsd: number;
};

/**
 * Defaults to active when absent. No pause/activate mutation is frozen (see DECISIONS-NEEDED.md).
 */
export type state3 = 'active' | 'paused';

export type SearchCriteria = {
    titlesInclude: Array<(string)>;
    titlesExclude: Array<(string)>;
    locations: Array<(string)>;
    /**
     * Machine tokens; client maps to display copy.
     */
    remotePolicy: 'remote-ok' | 'hybrid-ok' | 'required';
    maxCommuteMin: number;
    /**
     * Base salary floor
     */
    baseFloorUsd: number;
    /**
     * Base salary ceiling
     */
    baseCeilingUsd: number;
    /**
     * Lower bound of the years-experience band (was string "8-14 yrs").
     */
    yearsExperienceMin?: number;
    /**
     * Upper bound of the years-experience band.
     */
    yearsExperienceMax?: number;
    /**
     * D21 per-search override -- REPLACES the global eligible master set.
     */
    scoringResumeIds?: Array<(string)>;
};

/**
 * Machine tokens; client maps to display copy.
 */
export type remotePolicy = 'remote-ok' | 'hybrid-ok' | 'required';

export type Settings = {
    profile: {
        name: string;
        email: string;
        phone: string;
        timezone: string;
        currentRole: string;
        targetTitles: Array<(string)>;
        /**
         * Compensation floor
         */
        compFloorUsd: number;
    };
    integrations: Array<IntegrationRow>;
    providers: Array<ProviderRow>;
    routing: Array<RoutingRow>;
    usage: Array<UsageRow>;
    monthSpendUsd: number;
    monthlyCapUsd: number;
    privacy: Array<PrivacyToggle>;
    privacyLastUpdated: string;
    plan: {
        name: string;
        priceUsd: number;
        description: string;
        nextCharge: string;
    };
    invoices: Array<InvoiceRow>;
    notifPrefs: Array<NotifPref>;
    extensionTokens: Array<ExtensionToken>;
    emailParserFallback: EmailParserFallback;
};

export type ShortlistEntry = {
    /**
     * Shortlist entry id (DELETE /shortlist/{id}).
     */
    id: string;
    /**
     * FK -> Job.id (ADR-006).
     */
    jobId?: string;
    company: string;
    role: string;
    location: string;
    salary: (Salary | null);
    match: number;
    saved: string;
    source: 'you';
    why?: string;
    stale?: boolean;
};

export type source = 'you';

/**
 * Settled application-stage taxonomy (state-machines.md#application-stages is normative over the mock's coarser 8-value enum). Lowercase wire values; multiword stages use snake_case.
 *
 */
export type Stage = 'saved' | 'drafting' | 'applied' | 'screening' | 'interview' | 'offer' | 'won' | 'rejected' | 'ghosted' | 'withdrew' | 'dismissed' | 'offer_rescinded';

/**
 * One appended, immutable row of an application's stage-transition audit log. Corrections are compensating transitions referencing the prior row.
 *
 */
export type StageTransition = {
    id: string;
    applicationId: string;
    /**
     * Prior stage; null for the initial SAVED/DRAFTING entry.
     */
    fromStage?: (Stage | null);
    toStage: Stage;
    source: TransitionSource;
    reason?: string;
    /**
     * D16 chip reasons (dismiss/withdraw).
     */
    reasons?: Array<(string)>;
    /**
     * Resume snapshotted at APPLIED (required by the request when target is APPLIED).
     */
    resumeId?: (string) | null;
    createdAt: string;
};

export type TimelineEvent = {
    id: string;
    time: string;
    who: string;
    message: string;
    /**
     * COA-036 structured attribution (client renders the badge copy).
     */
    actor?: 'you' | 'coach-on-behalf' | 'agent';
};

/**
 * COA-036 structured attribution (client renders the badge copy).
 */
export type actor = 'you' | 'coach-on-behalf' | 'agent';

export type TransitionInput = {
    targetStage: Stage;
    /**
     * Optimistic-concurrency guard; must equal Application.version or 409 `conflict`.
     */
    expectedVersion: number;
    source?: (TransitionSource);
    reason?: string;
    reasons?: Array<(string)>;
    /**
     * Required when `targetStage` = applied (locks the submitted-resume snapshot).
     */
    resumeId?: string;
};

export type TransitionResult = {
    application: ApplicationView;
    transition: StageTransition;
};

/**
 * Who/what drove the transition (aligned with the settled machine sources).
 */
export type TransitionSource = 'user' | 'user_correction' | 'user_reactivation' | 'system';

export type TrashEntry = {
    kind: LibraryKind;
    id: string;
    label: string;
    deletedAt: string;
};

/**
 * One rung of the ladder. label/blurb were UI copy (client-owned).
 */
export type TrustTierRung = {
    tier: AgentTrustTier;
};

export type UsageAggregate = {
    monthSpendUsd: number;
    monthlyCapUsd: number;
    tokensIn: number;
    tokensOut: number;
    /**
     * Average spend per session
     */
    avgPerSessionUsd: number;
};

export type UsageRow = {
    service: string;
    model: string;
    count: number;
    tokens: number;
    costUsd: number;
};

export type User = {
    name: string;
    email: string;
    initials: string;
    city: string;
    current: string;
    years: number;
    comp_floor: number;
    target_titles: Array<(string)>;
};

export type RequestDataExportResponse = (DataExportRequest);

export type DeleteAccountResponse = ({
    gracePeriodEndsAt: string;
});

export type GetAgentsResponse = (Array<Agent>);

export type GetAgentData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetAgentResponse = (Agent);

export type PatchAgentData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        state?: AgentState;
        live?: boolean;
    };
};

export type PatchAgentResponse = (Agent);

export type GetAgentPermissionsData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetAgentPermissionsResponse = (Array<AgentPermission>);

export type GetAgentTrustTierData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetAgentTrustTierResponse = (AgentTrustTierView);

export type PatchAgentTrustTierData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        targetTier: AgentTrustTier;
    };
};

export type PatchAgentTrustTierResponse = (AgentTrustTierUpdate);

export type GetAgentLogData = {
    agentId?: string;
    kind?: AgentLogKind;
};

export type GetAgentLogResponse = (Array<AgentLogEntry>);

export type GetReviewQueueResponse = (Array<ReviewQueueItem>);

export type ApproveAgentActionData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type ApproveAgentActionResponse = (void);

export type RejectAgentActionData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type RejectAgentActionResponse = (void);

export type GetApplicationsData = {
    searchId?: string;
};

export type GetApplicationsResponse = (Array<ApplicationView>);

export type CreateApplicationData = {
    requestBody: CreateApplicationInput;
};

export type CreateApplicationResponse = (ApplicationView);

export type GetApplicationData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetApplicationResponse = (ApplicationView);

export type TransitionApplicationData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: TransitionInput;
};

export type TransitionApplicationResponse = (TransitionResult);

export type GetResumeSnapshotData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetResumeSnapshotResponse = (ResumeSnapshot);

export type MarkWonData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody?: MarkWonInput;
};

export type MarkWonResponse = (MarkWonResult);

export type UndoMarkWonData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        undoToken: string;
    };
};

export type UndoMarkWonResponse = (ApplicationView);

export type ReactivateApplicationData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type ReactivateApplicationResponse = (ApplicationView);

export type DismissApplicationData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody?: {
        reasons?: Array<(string)>;
    };
};

export type DismissApplicationResponse = (DismissResult);

export type GetApplicationTimelineData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetApplicationTimelineResponse = (Array<TimelineEvent>);

export type GetArchiveData = {
    /**
     * won -> outcome=won; passed -> outcome in (rejected, withdrawn).
     */
    kind: 'won' | 'passed';
};

export type GetArchiveResponse = (Array<ApplicationView>);

export type GetArchiveCountsResponse = ({
    won: number;
    passed: number;
});

export type GetCoachThreadsResponse = (Array<CoachThread>);

export type GetCoachThreadData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetCoachThreadResponse = ({
    thread: CoachThread;
    messages: Array<CoachMessage>;
    context: Array<ContextCard>;
});

export type ProposeCoachEditData = {
    requestBody: CoachSubject;
};

export type ProposeCoachEditResponse = (CoachProposal);

export type SaveCoachProposalData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: CoachProposal;
};

export type SaveCoachProposalResponse = (TimelineEvent);

export type GetInterviewRoundsData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetInterviewRoundsResponse = (Array<InterviewRound>);

export type PatchInterviewRoundData = {
    appId: string;
    requestBody: {
        date?: string;
        type?: InterviewType;
        format?: InterviewFormat;
        status?: InterviewStatus;
    };
    roundId: string;
};

export type PatchInterviewRoundResponse = (InterviewRound);

export type GetJobsResponse = (Array<Job>);

export type GetJobsInboxData = {
    searchId?: string;
};

export type GetJobsInboxResponse = (Array<JobInboxItem>);

export type GetJobData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetJobResponse = (Job);

export type GetContactsResponse = (Array<Contact>);

export type CreateContactData = {
    requestBody: ContactDraft;
};

export type CreateContactResponse = (Contact);

export type GetContactData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetContactResponse = (Contact);

export type UpdateContactData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: ContactDraft;
};

export type UpdateContactResponse = (Contact);

export type DeleteContactData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DeleteContactResponse = (void);

export type GetAccomplishmentsResponse = (Array<Accomplishment>);

export type CreateAccomplishmentData = {
    requestBody: AccomplishmentDraft;
};

export type CreateAccomplishmentResponse = (Accomplishment);

export type UpdateAccomplishmentData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: AccomplishmentDraft;
};

export type UpdateAccomplishmentResponse = (Accomplishment);

export type DeleteAccomplishmentData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DeleteAccomplishmentResponse = (void);

export type DeriveAccomplishmentFromProjectData = {
    requestBody: {
        projectId: string;
    };
};

export type DeriveAccomplishmentFromProjectResponse = (AccomplishmentDeriveResult);

export type GetAnswersResponse = (Array<Answer>);

export type CreateAnswerData = {
    requestBody: AnswerDraft;
};

export type CreateAnswerResponse = (Answer);

export type UpdateAnswerData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: AnswerDraft;
};

export type UpdateAnswerResponse = (Answer);

export type DeleteAnswerData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DeleteAnswerResponse = (void);

export type GetProjectsResponse = (Array<Project>);

export type CreateProjectData = {
    requestBody: ProjectDraft;
};

export type CreateProjectResponse = (Project);

export type UpdateProjectData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: ProjectDraft;
};

export type UpdateProjectResponse = (Project);

export type DeleteProjectData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DeleteProjectResponse = (void);

export type GetCredentialsResponse = (Array<Credential>);

export type GetTrashResponse = (Array<TrashEntry>);

export type RestoreLibraryItemData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    kind: LibraryKind;
};

export type RestoreLibraryItemResponse = (void);

export type PurgeLibraryItemData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    kind: LibraryKind;
};

export type PurgeLibraryItemResponse = (void);

export type GetDeletionImpactData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    kind: LibraryKind;
};

export type GetDeletionImpactResponse = (DeletionImpact);

export type PreviewDeepMatchScoreData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        resumeIds: Array<(string)>;
    };
};

export type PreviewDeepMatchScoreResponse = (CostPreview);

export type RunDeepMatchScoreData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        resumeId: string;
    };
};

export type RunDeepMatchScoreResponse = (DeepMatchResult);

export type GetMatchReportData = {
    jobId: string;
    resumeId: string;
};

export type GetMatchReportResponse = (MatchReport);

export type GetNotificationsResponse = (Array<Notification>);

export type MarkNotificationReadData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type MarkNotificationReadResponse = (Notification);

export type MarkAllNotificationsReadResponse = (Array<Notification>);

export type GetResumeUploadsResponse = (Array<ResumeUpload>);

export type GetCareerHistoryResponse = (Array<CareerHistoryItem>);

export type GetResumeTemplatesResponse = (Array<ResumeTemplate>);

export type GetResumeExportsResponse = (Array<ResumeExport>);

export type GetProjectionsResponse = (Array<Resume>);

export type CreateProjectionData = {
    requestBody: {
        name: string;
        targetRole?: string;
        itemIds: Array<(string)>;
        templateId?: string;
        sourceUploadId?: string;
    };
};

export type CreateProjectionResponse = (Resume);

export type AssignTemplateData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        templateId: string;
    };
};

export type AssignTemplateResponse = (Resume);

export type RenderExportData = {
    requestBody: {
        projectionId: string;
    };
};

export type RenderExportResponse = (ResumeExport);

export type RegenerateExportData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type RegenerateExportResponse = (ResumeExport);

export type GetResumesResponse = (Array<Resume>);

export type CreateResumeResponse = (Resume);

export type GetResumeData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetResumeResponse = (Resume);

export type PatchResumeData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        name?: string;
        body?: string;
        scoringEnabled?: boolean;
    };
};

export type PatchResumeResponse = (Resume);

export type DeleteResumeData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DeleteResumeResponse = (void);

export type DuplicateResumeData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DuplicateResumeResponse = (Resume);

export type SetDefaultResumeData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type SetDefaultResumeResponse = (Array<Resume>);

export type ForkResumeAsDraftData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        jobId: string;
    };
};

export type ForkResumeAsDraftResponse = (Resume);

export type GetSearchesResponse = (Array<Search>);

export type CreateSearchData = {
    requestBody: CreateSearchInput;
};

export type CreateSearchResponse = (Search);

export type GetSearchData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type GetSearchResponse = (Search);

export type UpdateSearchCriteriaData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
    requestBody: {
        criteria: SearchCriteria;
    };
};

export type UpdateSearchCriteriaResponse = (Search);

export type GetSettingsResponse = (Settings);

export type GetUsageAggregateResponse = (UsageAggregate);

export type GetShortlistData = {
    searchId?: string;
};

export type GetShortlistResponse = (Array<ShortlistEntry>);

export type AddToShortlistData = {
    requestBody: {
        jobId?: string;
        company: string;
        role: string;
        location: string;
        salary: (Salary | null);
        match: number;
    };
};

export type AddToShortlistResponse = (ShortlistEntry);

export type DismissFromShortlistData = {
    /**
     * Resource UUID (RFC 4122). Resolved by UUID only -- the mock's legacy slug/name leniency is not part of the contract.
     *
     */
    id: string;
};

export type DismissFromShortlistResponse = (void);

export type GetCurrentUserResponse = (User);