"""shortlist_entry table (B2, first composite-FK child)

Revision ID: 4317eb75f1cd
Revises: 4c17ea8b5656
Create Date: 2026-07-13 23:39:01.000508

The FIRST child table that composite-FKs a parent -- the exemplar sprint-04's
children (stage_transition, resume_snapshot, match_report) copy
(docs/sprints/sprint-03-spec.md). Copies the job exemplar's tenancy (RLS +
app_runtime + timestamptz + named JSONB CHECKs + schema_version + the
UNIQUE(user_id, id) anchor + CASCADE user FK). NET-NEW here:

* composite FK ``(user_id, job_id) -> job(user_id, id)`` (MATCH SIMPLE:
  enforced only when ``job_id`` is non-null, so a cross-tenant job_id fails at
  the DB; a NULL job_id is a legal display-only entry, matching the optional
  wire ``jobId``);
* PARTIAL dedup ``UNIQUE(user_id, job_id) WHERE job_id IS NOT NULL`` (v3's
  ``shortlist_entry unique (user_id, job_id)``; NULL-job rows are not deduped).

The composite FK, partial index, and RLS/policy live here (raw ``op.execute``),
NOT in the model metadata -- the DEBT-6 autogenerate caveat. NOTE the
autogenerate diff proposed dropping ``uq_job_user_source_url`` for the same
reason; that drop is intentionally NOT applied here.

``app_runtime`` needs no new grants (migration 075675058c67's ALTER DEFAULT
PRIVILEGES covers migration-created tables). Downgrade raises: forward-fix-only.
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4317eb75f1cd"
down_revision = "4c17ea8b5656"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortlist_entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("company", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "salary",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("match", sa.Integer(), nullable=False),
        sa.Column(
            "saved",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("why", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=True),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "salary IS NULL OR (jsonb_typeof(salary) = 'object' AND jsonb_typeof(salary->'extra') = 'array' AND (jsonb_typeof(salary->'value') = 'number'      OR (jsonb_typeof(salary->'min') = 'number'          AND jsonb_typeof(salary->'max') = 'number'))) IS TRUE",
            name="ck_shortlist_salary_shape",
        ),
        sa.CheckConstraint("source IN ('you')", name="ck_shortlist_source"),
        sa.CheckConstraint("schema_version >= 1", name="ck_shortlist_schema_version"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        # The composite FK is the sprint-03 exemplar: a nested job_id must belong
        # to the SAME tenant, enforced at the DB (MATCH SIMPLE -> skipped on NULL).
        sa.ForeignKeyConstraint(
            ["user_id", "job_id"], ["job.user_id", "job.id"], name="fk_shortlist_job"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "id", name="uq_shortlist_user_id_id"),
    )
    op.create_index(
        op.f("ix_shortlist_entry_user_id"), "shortlist_entry", ["user_id"], unique=False
    )
    # (Intentionally NOT dropping job's uq_job_user_source_url -- see the
    # module docstring / DEBT-6.)
    # ### end Alembic commands ###

    # PARTIAL dedup: at most one entry per (user_id, job_id) for real jobs;
    # NULL-job (display-only) entries are not deduped (PIN-2).
    op.execute(
        "CREATE UNIQUE INDEX uq_shortlist_user_job ON shortlist_entry"
        " (user_id, job_id) WHERE job_id IS NOT NULL"
    )

    # Row-level security -- copied from the job exemplar (PIN-7).
    op.execute("ALTER TABLE shortlist_entry ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE shortlist_entry FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY shortlist_tenant_isolation ON shortlist_entry
        FOR ALL
        USING (user_id = NULLIF(current_setting('app.user_id', true), '')::uuid)
        WITH CHECK (
            user_id = NULLIF(current_setting('app.user_id', true), '')::uuid
        )
        """
    )


def downgrade():
    raise RuntimeError(
        "forward-fix only: this project does not support downgrades"
        " (plan v3, Migrations)"
    )
