"""job table (B1 exemplar under binding conventions)

Revision ID: 4c17ea8b5656
Revises: 55770316f4ab
Create Date: 2026-07-13 19:08:10.119384

The FIRST populated-schema tenant table -- the exemplar later sprints copy
(docs/sprints/sprint-02-spec.md). Conventions carried (plan v3, Design
conventions):

* tenant ``user_id`` + composite ``UNIQUE(user_id, id)`` (the anchor future
  child tables composite-FK against, so cross-tenant nested ids fail at the
  DB);
* FORCE row-level security with a transaction-local ``app.user_id`` GUC
  policy, enforced under the ``app_runtime`` role (owner stays ``postgres``;
  superusers bypass RLS by definition -- documented, not pretended away);
* ``timestamptz`` everywhere, named JSONB CHECKs (bodies wrapped in
  ``(...) IS TRUE`` because CHECK treats NULL as satisfied), explicit
  ``schema_version``;
* the partial-unique dedup index ``(user_id, source_url) WHERE source_url IS
  NOT NULL`` reserved for captureJob (canonicalization is Release 0.2's
  concern).

``app_runtime`` needs no new grants here: migration 075675058c67's ALTER
DEFAULT PRIVILEGES already covers tables created by the migration role.
Downgrade raises: forward-fix-only policy (plan v3, Migrations).
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c17ea8b5656'
down_revision = '55770316f4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('work_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compensation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('posted', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    sa.CheckConstraint("(jsonb_typeof(employment) = 'object' AND employment->>'classification' IN ('w2', 'contract', '1099') AND employment->>'cadence' IN ('hourly', 'salary') AND employment->>'commitment' IN ('full-time', 'part-time')) IS TRUE", name='ck_job_employment_shape'),
    sa.CheckConstraint("(jsonb_typeof(location) = 'object' AND jsonb_typeof(location->'raw') = 'string' AND (NOT location ? 'locality'      OR jsonb_typeof(location->'locality') IN ('string', 'null')) AND (NOT location ? 'region'      OR jsonb_typeof(location->'region') IN ('string', 'null')) AND (NOT location ? 'country'      OR jsonb_typeof(location->'country') IN ('string', 'null'))) IS TRUE", name='ck_job_location_shape'),
    sa.CheckConstraint("(jsonb_typeof(source) = 'object' AND jsonb_typeof(source->'board') = 'string' AND source->>'channel' IN     ('url', 'jd-text', 'extension', 'email-forward') AND jsonb_typeof(source->'capturedAt') = 'string') IS TRUE", name='ck_job_source_shape'),
    sa.CheckConstraint("compensation IS NULL OR (jsonb_typeof(compensation) = 'object' AND jsonb_typeof(compensation->'extra') = 'array' AND (jsonb_typeof(compensation->'value') = 'number'      OR (jsonb_typeof(compensation->'min') = 'number'          AND jsonb_typeof(compensation->'max') = 'number'))) IS TRUE", name='ck_job_compensation_shape'),
    sa.CheckConstraint("requirements IS NULL OR jsonb_typeof(requirements) = 'array' IS TRUE", name='ck_job_requirements_array'),
    sa.CheckConstraint("tags IS NULL OR jsonb_typeof(tags) = 'array' IS TRUE", name='ck_job_tags_array'),
    sa.CheckConstraint("work_mode IN ('remote', 'hybrid', 'onsite')", name='ck_job_work_mode'),
    sa.CheckConstraint('"match" IS NULL OR (jsonb_typeof("match") = \'object\' AND jsonb_typeof("match"->\'score\') = \'number\') IS TRUE', name='ck_job_match_shape'),
    sa.CheckConstraint('schema_version >= 1', name='ck_job_schema_version'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_job_user_id_id')
    )
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Row-level security -- the systemic tenancy backstop (PIN-7). The policy
    # keys on the transaction-local ``app.user_id`` GUC; NULLIF guards the
    # empty-string case so an unset GUC yields zero rows, never an error.
    op.execute("ALTER TABLE job ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE job FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY job_tenant_isolation ON job
        FOR ALL
        USING (user_id = NULLIF(current_setting('app.user_id', true), '')::uuid)
        WITH CHECK (
            user_id = NULLIF(current_setting('app.user_id', true), '')::uuid
        )
        """
    )
    # Partial-unique dedup index reserved for captureJob (PIN-3): manual
    # captures without a URL carry NULL and are never deduped.
    op.execute(
        "CREATE UNIQUE INDEX uq_job_user_source_url ON job (user_id, source_url)"
        " WHERE source_url IS NOT NULL"
    )


def downgrade():
    raise RuntimeError(
        "forward-fix only: this project does not support downgrades"
        " (plan v3, Migrations)"
    )
