"""applications resume snapshot tables (B3 sprint-04)

Revision ID: 5f1fb22cd505
Revises: 4317eb75f1cd
Create Date: 2026-07-14 12:33:10.405716

Five tables for plan v3 Phase B item 3 (docs/sprints/sprint-04-spec.md):
``application``, ``stage_transition`` (append-only), minimal ``resume``,
``resume_snapshot`` (append-only), ``undo_grant``. Conventions copied from the
job (4c17ea8b5656) and shortlist (4317eb75f1cd) exemplars: tenant ``user_id``
+ CASCADE, ``UNIQUE(user_id, id)`` anchors, FORCE RLS on the ``app.user_id``
GUC, timestamptz, named ``(...) IS TRUE`` CHECKs, ``schema_version``.

NET-NEW here (spec PINs):

* composite FKs for every DB-entity reference (PIN-18): application ->
  job/resume/resume_snapshot, stage_transition -> application + the
  self-referential ``corrects_transition_id`` (PIN-3), resume_snapshot ->
  application/resume (PIN-17 delete backstop), undo_grant -> application/
  stage_transition, resume.fork_job_id -> job. All NO ACTION except the
  user_id CASCADEs (exemplar copy; user teardown resolves the diamond at
  statement end). search_id/source_upload_id/template_id have NO FK -- their
  targets stay mock through Release 0.1 (PIN-18).
* append-only enforcement: ``enforce_append_only('stage_transition')`` +
  ``('resume_snapshot')`` (075675058c67: REVOKE UPDATE/DELETE/TRUNCATE from
  app_runtime + owner-blocking triggers).
* PIN-19 hardened privilege matrix: app_runtime gets application
  SELECT+INSERT only (stage/version/outcome writes go through the single
  stage-mutation DB function, arriving in 3b); stage_transition,
  resume_snapshot, and undo_grant are SELECT-only (history and grants are
  forge-proof); resume keeps full DML (CRUD ops own it).
* partial unique ``uq_resume_user_default (user_id) WHERE tag='DEFAULT'``
  (PIN-5: at most one DEFAULT resume per tenant).

Composite FKs, partial index, RLS, append-only, and grants are raw
``op.execute`` -- the DEBT-6 autogenerate caveat. The autogenerate diff again
proposed dropping ``uq_job_user_source_url``, ``uq_shortlist_user_job``, and
``fk_shortlist_job`` (all migration-only artifacts); those drops are
intentionally NOT applied. Downgrade raises: forward-fix-only.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f1fb22cd505'
down_revision = '4317eb75f1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coach_nudge', sa.Boolean(), nullable=True),
    sa.Column('resurrected', sa.Boolean(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome_reasons', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('system_reasons', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('search_id', sa.Uuid(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("flag IS NULL OR flag IN ('stale', 'offer')", name='ck_application_flag'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('won', 'rejected', 'withdrawn')", name='ck_application_outcome'),
    sa.CheckConstraint("outcome_reasons IS NULL OR (jsonb_typeof(outcome_reasons) = 'array' AND jsonb_array_length(outcome_reasons) <= 8) IS TRUE", name='ck_application_outcome_reasons'),
    sa.CheckConstraint("stage IN ('saved', 'drafting', 'applied', 'screening', 'interview', 'offer', 'won', 'rejected', 'ghosted', 'withdrew', 'dismissed', 'offer_rescinded')", name='ck_application_stage'),
    sa.CheckConstraint("system_reasons IS NULL OR jsonb_typeof(system_reasons) = 'array' IS TRUE", name='ck_application_system_reasons'),
    sa.CheckConstraint('schema_version >= 1', name='ck_application_schema_version'),
    sa.CheckConstraint('version >= 1', name='ck_application_version'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_application_user_id_id')
    )
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used_in', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match', sa.Integer(), nullable=True),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_upload_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('target_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scoring_enabled', sa.Boolean(), nullable=True),
    sa.Column('fork_job_id', sa.Uuid(), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("tag IN ('MASTER', 'DEFAULT', 'VARIANT', 'TAILORED', 'DRAFT', 'FORMAT')", name='ck_resume_tag'),
    sa.CheckConstraint('schema_version >= 1', name='ck_resume_schema_version'),
    sa.CheckConstraint('used_in >= 0', name='ck_resume_used_in'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_resume_user_id_id')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_table('resume_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('template_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('schema_version >= 1', name='ck_resume_snapshot_schema_version'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'application_id', name='uq_resume_snapshot_application'),
    sa.UniqueConstraint('user_id', 'id', name='uq_resume_snapshot_user_id_id')
    )
    op.create_index(op.f('ix_resume_snapshot_user_id'), 'resume_snapshot', ['user_id'], unique=False)
    op.create_table('stage_transition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('from_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reasons', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('corrects_transition_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint("from_stage IS NULL OR from_stage IN ('saved', 'drafting', 'applied', 'screening', 'interview', 'offer', 'won', 'rejected', 'ghosted', 'withdrew', 'dismissed', 'offer_rescinded')", name='ck_stage_transition_from_stage'),
    sa.CheckConstraint("reasons IS NULL OR (jsonb_typeof(reasons) = 'array' AND jsonb_array_length(reasons) <= 8) IS TRUE", name='ck_stage_transition_reasons'),
    sa.CheckConstraint("source IN ('user', 'user_correction', 'user_reactivation', 'system')", name='ck_stage_transition_source'),
    sa.CheckConstraint("to_stage IN ('saved', 'drafting', 'applied', 'screening', 'interview', 'offer', 'won', 'rejected', 'ghosted', 'withdrew', 'dismissed', 'offer_rescinded')", name='ck_stage_transition_to_stage'),
    sa.CheckConstraint('schema_version >= 1', name='ck_stage_transition_schema_version'),
    sa.CheckConstraint('seq >= 1', name='ck_stage_transition_seq_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'application_id', 'seq', name='uq_stage_transition_seq'),
    sa.UniqueConstraint('user_id', 'id', name='uq_stage_transition_user_id_id')
    )
    op.create_index(op.f('ix_stage_transition_user_id'), 'stage_transition', ['user_id'], unique=False)
    op.create_table('undo_grant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('corrects_transition_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.CheckConstraint('schema_version >= 1', name='ck_undo_grant_schema_version'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'id', name='uq_undo_grant_user_id_id')
    )
    op.create_index(op.f('ix_undo_grant_user_id'), 'undo_grant', ['user_id'], unique=False)
    # (Intentionally NOT dropping uq_job_user_source_url, uq_shortlist_user_job,
    # or fk_shortlist_job -- DEBT-6 autogenerate false positives, hand-stripped.)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Composite tenant FKs (PIN-18): every reference to a DB entity fails
    # cross-tenant at the DB. Added AFTER all tables exist because
    # application <-> resume_snapshot reference each other.
    # ------------------------------------------------------------------
    op.execute(
        "ALTER TABLE application ADD CONSTRAINT fk_application_job"
        " FOREIGN KEY (user_id, job_id) REFERENCES job (user_id, id)"
    )
    op.execute(
        "ALTER TABLE application ADD CONSTRAINT fk_application_resume"
        " FOREIGN KEY (user_id, resume_id) REFERENCES resume (user_id, id)"
    )
    op.execute(
        "ALTER TABLE application ADD CONSTRAINT fk_application_snapshot"
        " FOREIGN KEY (user_id, submitted_snapshot_id)"
        " REFERENCES resume_snapshot (user_id, id)"
    )
    op.execute(
        "ALTER TABLE stage_transition ADD CONSTRAINT fk_stage_transition_application"
        " FOREIGN KEY (user_id, application_id) REFERENCES application (user_id, id)"
    )
    op.execute(
        "ALTER TABLE stage_transition ADD CONSTRAINT fk_stage_transition_corrects"
        " FOREIGN KEY (user_id, corrects_transition_id)"
        " REFERENCES stage_transition (user_id, id)"
    )
    op.execute(
        "ALTER TABLE resume_snapshot ADD CONSTRAINT fk_resume_snapshot_application"
        " FOREIGN KEY (user_id, application_id) REFERENCES application (user_id, id)"
    )
    op.execute(
        "ALTER TABLE resume_snapshot ADD CONSTRAINT fk_resume_snapshot_resume"
        " FOREIGN KEY (user_id, resume_id) REFERENCES resume (user_id, id)"
    )
    op.execute(
        "ALTER TABLE undo_grant ADD CONSTRAINT fk_undo_grant_application"
        " FOREIGN KEY (user_id, application_id) REFERENCES application (user_id, id)"
    )
    op.execute(
        "ALTER TABLE undo_grant ADD CONSTRAINT fk_undo_grant_corrects"
        " FOREIGN KEY (user_id, corrects_transition_id)"
        " REFERENCES stage_transition (user_id, id)"
    )
    op.execute(
        "ALTER TABLE resume ADD CONSTRAINT fk_resume_fork_job"
        " FOREIGN KEY (user_id, fork_job_id) REFERENCES job (user_id, id)"
    )

    # At most one DEFAULT resume per tenant (PIN-5 backstop).
    op.execute(
        "CREATE UNIQUE INDEX uq_resume_user_default ON resume (user_id)"
        " WHERE tag = 'DEFAULT'"
    )

    # ------------------------------------------------------------------
    # Row-level security -- copied from the job exemplar, one policy per table.
    # ------------------------------------------------------------------
    for table, policy in (
        ("application", "application_tenant_isolation"),
        ("stage_transition", "stage_transition_tenant_isolation"),
        ("resume", "resume_tenant_isolation"),
        ("resume_snapshot", "resume_snapshot_tenant_isolation"),
        ("undo_grant", "undo_grant_tenant_isolation"),
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {policy} ON {table}
            FOR ALL
            USING (user_id = NULLIF(current_setting('app.user_id', true), '')::uuid)
            WITH CHECK (
                user_id = NULLIF(current_setting('app.user_id', true), '')::uuid
            )
            """
        )

    # ------------------------------------------------------------------
    # Append-only enforcement (075675058c67 machinery): REVOKE UPDATE/DELETE/
    # TRUNCATE from app_runtime + triggers that block even the owner.
    # ------------------------------------------------------------------
    op.execute("SELECT enforce_append_only('stage_transition')")
    op.execute("SELECT enforce_append_only('resume_snapshot')")

    # ------------------------------------------------------------------
    # PIN-19 hardened privilege matrix (the ALTER DEFAULT PRIVILEGES grant
    # from 075675058c67 gave app_runtime full DML on these; narrow it).
    # application: stage/version/outcome writes go ONLY through the 3b
    # stage-mutation function; the row itself is never runtime-deleted
    # (PIN-14 soft-remove). History and grants are forge-proof: written
    # exclusively by the function as owner.
    # ------------------------------------------------------------------
    op.execute("REVOKE UPDATE, DELETE ON application FROM app_runtime")
    op.execute("REVOKE INSERT ON stage_transition FROM app_runtime")
    op.execute("REVOKE INSERT ON resume_snapshot FROM app_runtime")
    op.execute("REVOKE INSERT, UPDATE, DELETE ON undo_grant FROM app_runtime")


def downgrade():
    raise RuntimeError(
        "forward-fix only: this project does not support downgrades"
        " (plan v3, Migrations)"
    )
