"""add profile fields to user

Revision ID: 70eafafea7af
Revises: fe56fa70289e
Create Date: 2026-07-07 14:36:20.207265

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70eafafea7af'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('initials', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True))
    op.add_column('user', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('current', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('years', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('comp_floor', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('target_titles', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'target_titles')
    op.drop_column('user', 'comp_floor')
    op.drop_column('user', 'years')
    op.drop_column('user', 'current')
    op.drop_column('user', 'city')
    op.drop_column('user', 'initials')
    # ### end Alembic commands ###
