# generated by datamodel-codegen:
#   filename:  mvp-api.yaml

from datetime import date as date_aliased
from enum import StrEnum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class Kind(StrEnum):
    not_found = "not_found"
    unauthorized = "unauthorized"
    validation_error = "validation_error"
    conflict = "conflict"
    cap_reached = "cap_reached"
    undo_window_expired = "undo_window_expired"
    invalid_transition = "invalid_transition"
    rate_limited = "rate_limited"
    provider_unavailable = "provider_unavailable"


class Error(BaseModel):
    kind: Kind
    path: str
    message: str | None = None


class AiRunStatus(StrEnum):
    """
    Wire status is always terminal (synchronous execution). The full 5-state lifecycle (queued/running/...) is a server-side telemetry concern on the persisted run record, not exposed on the response.

    """

    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class AiRunEnvelope(BaseModel):
    """
    Telemetry envelope embedded (as `aiRun`) in every AI operation's response. Execution is synchronous; `status` is terminal (`succeeded`/`failed`/`cancelled`) by the time the response returns.

    """

    provider: str
    """
    e.g. claude_cli
    """
    model: str
    status: AiRunStatus
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    durationMs: int | None = None
    estimatedCostUsd: float
    actualCostUsd: float | None = None
    synthetic: bool
    """
    True iff produced by the FakeProvider (never satisfies evidence/approval).
    """


class User(BaseModel):
    name: str
    email: EmailStr
    initials: str
    city: str
    current: str
    years: float
    comp_floor: float
    target_titles: list[str]


class Stage(StrEnum):
    """
    Settled application-stage taxonomy (state-machines.md#application-stages is normative over the mock's coarser 8-value enum). Lowercase wire values; multiword stages use snake_case.

    """

    saved = "saved"
    drafting = "drafting"
    applied = "applied"
    screening = "screening"
    interview = "interview"
    offer = "offer"
    won = "won"
    rejected = "rejected"
    ghosted = "ghosted"
    withdrew = "withdrew"
    dismissed = "dismissed"
    offer_rescinded = "offer_rescinded"


class TransitionSource(StrEnum):
    """
    Who/what drove the transition (aligned with the settled machine sources).
    """

    user = "user"
    user_correction = "user_correction"
    user_reactivation = "user_reactivation"
    system = "system"


class StageTransition(BaseModel):
    """
    One appended, immutable row of an application's stage-transition audit log. Corrections are compensating transitions referencing the prior row.

    """

    id: UUID
    applicationId: UUID
    fromStage: Stage | None = None
    """
    Prior stage; null for the initial SAVED/DRAFTING entry.
    """
    toStage: Stage
    source: TransitionSource
    reason: str | None = None
    reasons: list[str] | None = Field(None, max_length=8)
    """
    D16 chip reasons (dismiss/withdraw).
    """
    resumeId: UUID | None = None
    """
    Resume snapshotted at APPLIED (required by the request when target is APPLIED).
    """
    createdAt: AwareDatetime


class TransitionInput(BaseModel):
    targetStage: Stage
    expectedVersion: int
    """
    Optimistic-concurrency guard; must equal Application.version or 409 `conflict`.
    """
    source: TransitionSource | None = TransitionSource.user
    reason: str | None = None
    reasons: list[str] | None = Field(None, max_length=8)
    resumeId: UUID | None = None
    """
    Required when `targetStage` = applied (locks the submitted-resume snapshot).
    """


class ApplicationFlag(StrEnum):
    stale = "stale"
    offer = "offer"


class SalaryPoint(BaseModel):
    value: int
    """
    Full dollars.
    """
    extra: list[str]


class SalaryRange(BaseModel):
    min: int
    """
    Full dollars.
    """
    max: int
    """
    Full dollars.
    """
    extra: list[str]


class Outcome(StrEnum):
    """
    ORI-009 archive bucket; present only on archived entries.
    """

    won = "won"
    rejected = "rejected"
    withdrawn = "withdrawn"


class Application(BaseModel):
    """
    Stored application record (ADR-006 stage 3, fully normalized).
    """

    id: UUID
    jobId: UUID
    """
    FK -> Job.id.
    """
    resumeId: UUID | None
    """
    FK -> Resume.id; null when none yet.
    """
    stage: Stage
    version: int
    """
    Optimistic-concurrency counter; bumped on every transition (see TransitionInput.expectedVersion).
    """
    createdAt: AwareDatetime
    """
    Replaces the mock's relative `days`; the client derives age.
    """
    flag: ApplicationFlag | None = None
    contact: str | None = None
    coachNudge: bool | None = None
    resurrected: bool | None = None
    outcome: Outcome | None = None
    """
    ORI-009 archive bucket; present only on archived entries.
    """
    outcomeAt: AwareDatetime | None = None
    outcomeReason: str | None = None
    outcomeReasons: list[str] | None = Field(None, max_length=8)
    """
    D16 user-chosen reason chips (max 8).
    """
    systemReasons: list[str] | None = None
    """
    D16 system-applied chips -- separate tier, not counted in the user 8.
    """
    submittedSnapshotId: str | None = None
    """
    D10 FK -> ResumeSnapshot.id, set at APPLIED.
    """
    searchId: UUID | None = None
    """
    D15 FK -> Search.id (non-null in practice).
    """


class CreateApplicationInput(BaseModel):
    company: str
    role: str
    location: str
    salary: SalaryPoint | SalaryRange | None
    match: int
    source: str
    resumeId: UUID | None = None
    """
    Selected resume; null when none yet.
    """
    searchId: UUID | None = None
    """
    D15 target saved search; defaults to last-used / auto-created "My jobs".
    """


class MarkWonInput(BaseModel):
    startDate: date_aliased | None = None
    negotiatedComp: SalaryPoint | SalaryRange | None = None
    """
    Negotiated compensation; structured Salary carries qualifiers (equity, sign-on) via SalaryPoint.extra.
    """
    whatWorked: str | None = None


class Outcome1(StrEnum):
    """
    removed = pre-commit delete; withdrew = post-APPLIED archive.
    """

    removed = "removed"
    withdrew = "withdrew"


class DismissResult(BaseModel):
    outcome: Outcome1
    """
    removed = pre-commit delete; withdrew = post-APPLIED archive.
    """


class Actor(StrEnum):
    """
    COA-036 structured attribution (client renders the badge copy).
    """

    you = "you"
    coach_on_behalf = "coach-on-behalf"
    agent = "agent"


class TimelineEvent(BaseModel):
    id: UUID
    time: AwareDatetime
    who: str
    message: str
    actor: Actor | None = None
    """
    COA-036 structured attribution (client renders the badge copy).
    """


class InterviewType(StrEnum):
    recruiter_screen = "recruiter-screen"
    technical = "technical"
    onsite = "onsite"
    final = "final"


class InterviewFormat(StrEnum):
    video = "video"
    phone = "phone"
    onsite = "onsite"


class InterviewStatus(StrEnum):
    scheduled = "scheduled"
    completed = "completed"
    cancelled = "cancelled"


class InterviewRound(BaseModel):
    id: UUID
    appId: UUID
    date: AwareDatetime
    type: InterviewType
    format: InterviewFormat
    status: InterviewStatus


class ResumeSnapshot(BaseModel):
    """
    D10 immutable copy of the resume captured at APPLIED.
    """

    id: UUID
    applicationId: UUID
    resumeId: UUID
    name: str
    body: str
    templateVersion: str
    """
    D17 provenance.
    """
    capturedAt: AwareDatetime


class Source(StrEnum):
    you = "you"


class ShortlistEntry(BaseModel):
    id: UUID
    """
    Shortlist entry id (DELETE /shortlist/{id}).
    """
    jobId: UUID | None = None
    """
    FK -> Job.id (ADR-006).
    """
    company: str
    role: str
    location: str
    salary: SalaryPoint | SalaryRange | None
    match: int
    saved: AwareDatetime
    source: Source
    why: str | None = None
    stale: bool | None = None


class JobCaptureMethod(StrEnum):
    url = "url"
    jd_text = "jd-text"
    extension = "extension"
    email_forward = "email-forward"


class JobWorkMode(StrEnum):
    remote = "remote"
    hybrid = "hybrid"
    onsite = "onsite"


class JobInboxItem(BaseModel):
    jobId: UUID | None = None
    company: str
    role: str
    location: str
    salary: SalaryPoint | SalaryRange | None
    match: int
    source: str
    """
    Origin board (greenhouse
    """
    isNew: bool | None = None
    posted: AwareDatetime
    capturedVia: JobCaptureMethod | None = None
    capturedAt: AwareDatetime | None = None
    sourceUrl: AnyUrl | None = None
    workMode: JobWorkMode | None = None
    employmentType: str | None = None
    seniority: str | None = None
    summary: str | None = None
    tags: list[str] | None = None
    requirements: list[str] | None = None
    strengths: list[str] | None = None
    gaps: list[str] | None = None
    jd: str | None = None
    """
    Raw JD text
    """


class Classification(StrEnum):
    w2 = "w2"
    contract = "contract"
    field_1099 = "1099"


class Cadence(StrEnum):
    hourly = "hourly"
    salary = "salary"


class Commitment(StrEnum):
    full_time = "full-time"
    part_time = "part-time"


class Employment(BaseModel):
    """
    ADR-006 -- three independent atomic axes.
    """

    classification: Classification
    cadence: Cadence
    commitment: Commitment


class JobLocation(BaseModel):
    raw: str
    locality: str | None = None
    region: str | None = None
    country: str | None = None


class JobSource(BaseModel):
    board: str
    channel: JobCaptureMethod
    url: AnyUrl | None = None
    capturedAt: AwareDatetime


class Kind1(StrEnum):
    """
    D8 -- rough = free local heuristic; deep = paid LLM. Absent = rough.
    """

    rough = "rough"
    deep = "deep"


class JobMatch(BaseModel):
    score: int
    strengths: list[str]
    gaps: list[str]
    kind: Kind1 | None = None
    """
    D8 -- rough = free local heuristic; deep = paid LLM. Absent = rough.
    """


class Job(BaseModel):
    """
    A captured posting -- the canonical resource (ADR-006).
    """

    id: UUID
    company: str
    title: str
    location: JobLocation
    workMode: JobWorkMode
    employment: Employment
    compensation: SalaryPoint | SalaryRange | None
    seniority: str | None = None
    source: JobSource
    isNew: bool | None = None
    posted: AwareDatetime
    summary: str | None = None
    tags: list[str] | None = None
    requirements: list[str] | None = None
    description: str | None = None
    """
    Verbatim JD text.
    """
    match: JobMatch | None = None


class MatchRubricRow(BaseModel):
    label: str
    score: int
    note: str


class Severity(StrEnum):
    high = "high"
    medium = "medium"
    low = "low"


class MatchGap(BaseModel):
    severity: Severity
    text: str


class MatchReport(BaseModel):
    resumeId: UUID
    jobId: UUID
    score: int
    rubric: list[MatchRubricRow]
    gaps: list[MatchGap]
    strengths: list[str]


class CostPreviewItem(BaseModel):
    resumeId: UUID
    """
    The resume this line prices (label was UI copy).
    """
    model: str
    estCostUsd: float


class CostPreview(BaseModel):
    """
    D8b consent panel payload, returned before any paid LLM run.
    """

    items: list[CostPreviewItem]
    totalUsd: float
    capRemainingUsd: float
    overCap: bool


class Kind2(StrEnum):
    deep = "deep"


class DeepMatchResult(BaseModel):
    jobId: UUID
    resumeId: UUID
    score: int
    kind: Kind2
    strengths: list[str]
    gaps: list[str]
    costUsd: float
    aiRun: AiRunEnvelope


class AgentState(StrEnum):
    running = "running"
    demand = "demand"
    paused = "paused"
    error = "error"


class AgentTrustTier(StrEnum):
    observe = "observe"
    suggest = "suggest"
    act_with_approval = "act-with-approval"
    autonomous = "autonomous"


class Agent(BaseModel):
    id: UUID
    name: str
    state: AgentState
    lastActivity: AwareDatetime
    actions: int
    costUsd: float
    """
    Agent's month-to-date cost
    """
    description: str
    live: bool | None = None
    trustTier: AgentTrustTier | None = None


class TrustTierRung(BaseModel):
    """
    One rung of the ladder. label/blurb were UI copy (client-owned).
    """

    tier: AgentTrustTier


class AgentTrustTierView(BaseModel):
    agentId: UUID
    currentTier: AgentTrustTier
    unlockedAt: AwareDatetime | None = None
    ladder: list[TrustTierRung]


class AgentTrustTierUpdate(BaseModel):
    agentId: UUID
    currentTier: AgentTrustTier
    status: str
    """
    State model DEFERRED (founder ruled 2026-07-04, DECISIONS-NEEDED
    """
    message: str


class AgentLogKind(StrEnum):
    auto = "auto"
    await_ = "await"
    success = "success"
    skipped = "skipped"


class AgentLogEntry(BaseModel):
    time: AwareDatetime
    agentId: UUID
    kind: AgentLogKind
    message: str
    ref: str
    """
    Opaque cross-reference to the acted-upon entity.
    """


class AgentPermission(BaseModel):
    permission: str
    granted: bool
    requiredTier: AgentTrustTier | None = None


class ReviewQueueItem(BaseModel):
    id: UUID
    """
    Queue entry id (approve/reject by /agents/review-queue/{id}).
    """
    agentId: UUID
    message: str
    time: AwareDatetime


class ResumeTag(StrEnum):
    MASTER = "MASTER"
    DEFAULT = "DEFAULT"
    VARIANT = "VARIANT"
    TAILORED = "TAILORED"
    DRAFT = "DRAFT"
    FORMAT = "FORMAT"


class Resume(BaseModel):
    """
    In the resume-lifecycle model (RES-034, ADR-007/008) a non-FORMAT Resume IS a projection -- a curated selection over career history.

    """

    id: UUID
    name: str
    subtitle: str
    """
    User-visible resume descriptor (data
    """
    version: str
    usedIn: int
    updated: AwareDatetime
    tag: ResumeTag
    match: int | None = None
    body: str | None = None
    sourceUploadId: UUID | None = None
    """
    RES-034 upload provenance.
    """
    templateId: UUID | None = None
    """
    TPL-002 render template.
    """
    targetRole: str | None = None
    scoringEnabled: bool | None = None
    """
    D21 -- participates in match scoring; default ON, MASTER-only.
    """


class ResumeUpload(BaseModel):
    id: UUID
    filename: str
    uploadedAt: AwareDatetime
    parsed: bool
    sizeBytes: int


class Kind3(StrEnum):
    experience = "experience"
    education = "education"
    skill = "skill"
    project = "project"
    summary = "summary"


class CareerHistoryItem(BaseModel):
    id: UUID
    kind: Kind3
    title: str
    org: str | None = None
    bullets: list[str]
    ordinal: int
    sourceUploadIds: list[UUID]
    """
    RES-038 merge provenance.
    """


class ResumeExport(BaseModel):
    id: UUID
    projectionId: UUID
    templateId: UUID
    templateVersion: str
    """
    D17 -- frozen per export.
    """
    filename: str
    generatedAt: AwareDatetime
    regenerable: bool


class PreviewKind(StrEnum):
    single_column = "single-column"
    two_column = "two-column"
    compact = "compact"
    modern = "modern"


class ResumeTemplate(BaseModel):
    id: UUID
    name: str
    previewKind: PreviewKind
    description: str


class CoachThreadScope(StrEnum):
    """
    Note `résumé` with é -- verbatim from source; fixtures depend on the spelling.
    """

    application = "application"
    résumé = "résumé"
    career_history = "career-history"
    projection = "projection"
    contact = "contact"
    answer = "answer"
    project = "project"
    accomplishment = "accomplishment"
    prep = "prep"
    general = "general"


class CoachThread(BaseModel):
    id: UUID
    title: str
    """
    Thread title (data
    """
    scope: CoachThreadScope
    when: AwareDatetime
    active: bool | None = None


class Author(StrEnum):
    user = "user"
    bot = "bot"


class Kind4(StrEnum):
    resume = "resume"
    cover_letter = "cover-letter"
    file = "file"


class DraftAttachment(BaseModel):
    name: str
    kind: Kind4


class CoachMessage(BaseModel):
    id: str
    author: Author
    text: str
    draft: str | None = None
    draftAttachments: list[DraftAttachment] | None = None
    """
    COA-024 -- items to attach when sending from the user's OWN email client.
    """
    typing: bool | None = None


class ContextCard(BaseModel):
    label: str
    body: str


class CoachSubject(BaseModel):
    """
    COA-031 -- the live "what am I looking at" descriptor.
    """

    scope: CoachThreadScope
    id: str | None = None
    label: str


class CoachDiff(BaseModel):
    field: str
    before: str
    after: str


class CoachProposal(BaseModel):
    """
    COA-032 -- reviewed (gate 1) before it is saved (gate 2).
    """

    id: str
    subject: CoachSubject
    summary: str
    diff: list[CoachDiff]
    status: str
    """
    State model DEFERRED (founder ruled 2026-07-04, DECISIONS-NEEDED
    """


class Link(BaseModel):
    label: str
    url: AnyUrl


class ContactDraft(BaseModel):
    name: str
    role: str
    org: str
    email: str
    phone: str
    relationship: str
    isReference: bool
    """
    References are a tagged role (CON-002).
    """
    tags: list[str]
    links: list[Link]
    notes: str


class Source1(BaseModel):
    """
    ACC-002 -- set when distilled from a Project (snapshot + backlink), else null.
    """

    projectId: UUID


class AccomplishmentDraft(BaseModel):
    title: str
    summary: str
    tags: list[str]
    source: Source1 | None
    """
    ACC-002 -- set when distilled from a Project (snapshot + backlink), else null.
    """


class Category(StrEnum):
    compensation = "compensation"
    motivation = "motivation"
    work_authorization = "work-authorization"
    logistics = "logistics"
    eeo = "eeo"
    other = "other"


class AnswerDraft(BaseModel):
    question: str
    body: str
    category: Category
    tags: list[str]


class ProjectDraft(BaseModel):
    """
    PRJ-001 -- a per-employer brain-dump / evidence reservoir.
    """

    title: str
    employer: str
    body: str
    tags: list[str]


class Type(StrEnum):
    license = "license"
    certification = "certification"
    transcript = "transcript"
    portfolio = "portfolio"
    other = "other"


class Credential(BaseModel):
    id: UUID
    name: str
    type: Type
    issuer: str
    expiry: date_aliased | None = None
    fileRef: str
    updated: AwareDatetime


class LibraryKind(StrEnum):
    contact = "contact"
    accomplishment = "accomplishment"
    answer = "answer"
    project = "project"


class TrashEntry(BaseModel):
    kind: LibraryKind
    id: UUID
    label: str
    deletedAt: AwareDatetime


class Item(BaseModel):
    id: UUID
    label: str


class Dependent(BaseModel):
    kind: LibraryKind
    count: int
    items: list[Item]


class DeletionImpact(BaseModel):
    kind: LibraryKind
    id: UUID
    dependents: list[Dependent]
    total: int


class RemotePolicy(StrEnum):
    """
    Machine tokens; client maps to display copy.
    """

    remote_ok = "remote-ok"
    hybrid_ok = "hybrid-ok"
    required = "required"


class SearchCriteria(BaseModel):
    titlesInclude: list[str]
    titlesExclude: list[str]
    locations: list[str]
    remotePolicy: RemotePolicy
    """
    Machine tokens; client maps to display copy.
    """
    maxCommuteMin: int
    baseFloorUsd: float
    """
    Base salary floor
    """
    baseCeilingUsd: float
    """
    Base salary ceiling
    """
    yearsExperienceMin: int | None = None
    """
    Lower bound of the years-experience band (was string "8-14 yrs").
    """
    yearsExperienceMax: int | None = None
    """
    Upper bound of the years-experience band.
    """
    scoringResumeIds: list[UUID] | None = None
    """
    D21 per-search override -- REPLACES the global eligible master set.
    """


class State(StrEnum):
    """
    Defaults to active when absent. No pause/activate mutation is frozen (see DECISIONS-NEEDED.md).
    """

    active = "active"
    paused = "paused"


class Search(BaseModel):
    id: UUID
    name: str
    state: State | None = None
    """
    Defaults to active when absent. No pause/activate mutation is frozen (see DECISIONS-NEEDED.md).
    """
    criteria: SearchCriteria
    jobsInInbox: int
    activeApplications: int
    shortlisted: int
    offers: int
    spendMoUsd: float
    """
    Month-to-date spend for this search
    """


class CreateSearchInput(BaseModel):
    name: str
    criteria: SearchCriteria
    """
    Partial criteria; unset fields take blank defaults.
    """


class Kind5(StrEnum):
    reply = "reply"
    agent = "agent"
    match = "match"
    cal = "cal"


class Notification(BaseModel):
    id: UUID
    kind: Kind5
    title: str
    message: str
    actor: str
    unread: bool | None = None


class State1(StrEnum):
    connected = "connected"
    not_connected = "not-connected"
    auto = "auto"


class IntegrationRow(BaseModel):
    name: str
    description: str
    state: State1
    account: str | None = None
    lastSync: AwareDatetime | None = None


class State2(StrEnum):
    connected = "connected"
    not_connected = "not-connected"
    error = "error"


class ProviderRow(BaseModel):
    provider: str
    model: str
    state: State2
    balanceUsd: float | None = None
    """
    Prepaid provider balance
    """
    error: str | None = None


class RoutingRow(BaseModel):
    """
    Per-task provider routing (label/value were generic display pairs; now semantic).
    """

    task: str
    """
    Task key
    """
    model: str
    """
    Model routed to that task.
    """


class UsageRow(BaseModel):
    service: str
    model: str
    count: int
    tokens: int
    costUsd: float


class PrivacyToggle(BaseModel):
    """
    Toggle STATE is data; the title/description copy is client-owned, keyed off `key`.

    """

    key: str
    """
    Stable toggle key the client maps to copy.
    """
    on: bool


class InvoiceRow(BaseModel):
    date: AwareDatetime
    description: str
    amountUsd: float


class NotifPref(BaseModel):
    id: str
    category: str
    """
    Category key (data; client owns the consequence copy).
    """
    emailEnabled: bool
    inAppEnabled: bool
    emailLocked: bool | None = None


class ExtensionToken(BaseModel):
    id: UUID
    label: str
    createdAt: AwareDatetime
    revokedAt: AwareDatetime | None = None


class Mode(StrEnum):
    deterministic = "deterministic"
    cheap_model = "cheap-model"


class EmailParserFallback(BaseModel):
    """
    D9b -- parser behavior once the monthly cap is hit.
    """

    mode: Mode
    model: str | None = None
    """
    Cheap model id, present when mode = cheap-model.
    """


class Profile(BaseModel):
    name: str
    email: EmailStr
    phone: str
    timezone: str
    currentRole: str
    targetTitles: list[str]
    compFloorUsd: float
    """
    Compensation floor
    """


class Plan(BaseModel):
    name: str
    priceUsd: float
    description: str
    nextCharge: AwareDatetime


class Settings(BaseModel):
    profile: Profile
    integrations: list[IntegrationRow]
    providers: list[ProviderRow]
    routing: list[RoutingRow]
    usage: list[UsageRow]
    monthSpendUsd: float
    monthlyCapUsd: float
    privacy: list[PrivacyToggle]
    privacyLastUpdated: AwareDatetime
    plan: Plan
    invoices: list[InvoiceRow]
    notifPrefs: list[NotifPref]
    extensionTokens: list[ExtensionToken]
    emailParserFallback: EmailParserFallback


class UsageAggregate(BaseModel):
    monthSpendUsd: float
    monthlyCapUsd: float
    tokensIn: int
    tokensOut: int
    avgPerSessionUsd: float
    """
    Average spend per session
    """


class DataExportRequest(BaseModel):
    url: AnyUrl
    requestedAt: AwareDatetime


class ApplicationView(Application):
    """
    Read model -- an Application joined with its Job and Resume (equivalent of GET /applications/{id}?expand=job,resume) with the job's display fields flattened on.

    """

    job: Job
    resume: Resume | None
    company: str
    role: str
    location: str
    salary: SalaryPoint | SalaryRange | None
    match: int
    source: str
    """
    Origin ATS/board (greenhouse
    """
    resumeName: str


class MarkWonResult(BaseModel):
    application: ApplicationView
    undoToken: UUID
    undoExpiresAt: AwareDatetime
    undoWindowSeconds: int
    """
    300 in the mock.
    """


class Contact(ContactDraft):
    id: UUID
    updated: AwareDatetime
    deletedAt: AwareDatetime | None = None
    """
    D24 soft-delete marker; set = in the trash.
    """


class Accomplishment(AccomplishmentDraft):
    id: UUID
    usedIn: int
    updated: AwareDatetime
    deletedAt: AwareDatetime | None = None


class AccomplishmentDeriveResult(BaseModel):
    """
    Response of deriveAccomplishmentFromProject (AI op); the accomplishment plus its run telemetry.
    """

    accomplishment: Accomplishment
    aiRun: AiRunEnvelope


class Answer(AnswerDraft):
    id: UUID
    updated: AwareDatetime
    deletedAt: AwareDatetime | None = None


class Project(ProjectDraft):
    id: UUID
    updated: AwareDatetime
    deletedAt: AwareDatetime | None = None


class TransitionResult(BaseModel):
    application: ApplicationView
    transition: StageTransition
